import type { Tutor } from "./TutorCarousel";

export const TUTORS: Tutor[] = [
  {
    name: "Nova",
    domain: "Mathematics",
    color: "#7C3AED",
    bg: "from-violet-500 to-purple-600",
    tagline: "Numbers come alive with Nova.",
    bullets: [
      "Adaptive problem sets that grow with the learner",
      "Visual math manipulatives for hands-on discovery",
      "Real-time hint system with multiple approaches",
    ],
    img: "/images/tutors/nova.png",
  },
  {
    name: "Sage",
    domain: "English Language Arts",
    color: "#10B981",
    bg: "from-emerald-500 to-green-600",
    tagline: "Every child has a story worth telling.",
    bullets: [
      "Turns reading comprehension into detective work",
      "Writing workshops with encouraging, constructive feedback",
      "Vocabulary building woven naturally into engaging stories",
    ],
    img: "/images/tutors/sage.png",
  },
  {
    name: "Spark",
    domain: "Science",
    color: "#F59E0B",
    bg: "from-amber-400 to-orange-500",
    tagline: "Curiosity is the best experiment.",
    bullets: [
      "Interactive virtual labs and simulations",
      "Guided scientific method explorations",
      "Connects concepts to real-world phenomena",
    ],
    img: "/images/tutors/spark.png",
  },
  {
    name: "Chrono",
    domain: "History & Social Studies",
    color: "#6366F1",
    bg: "from-indigo-500 to-blue-600",
    tagline: "Travel through time, one lesson at a time.",
    bullets: [
      "Immersive timeline-based adventures",
      "Primary source analysis made engaging",
      "Cultural perspectives and critical thinking",
    ],
    img: "/images/tutors/chrono.png",
  },
  {
    name: "Pixel",
    domain: "Coding & Technology",
    color: "#06B6D4",
    bg: "from-cyan-500 to-teal-600",
    tagline: "Build the future, one block at a time.",
    bullets: [
      "Block-based to text-based coding progression",
      "Game design and interactive project creation",
      "Computational thinking across subjects",
    ],
    img: "/images/tutors/pixel.png",
  },
  {
    name: "Echo",
    domain: "Speech & Communication",
    color: "#EC4899",
    bg: "from-pink-500 to-rose-600",
    tagline: "Find your voice, at your own pace.",
    bullets: [
      "AAC-integrated communication support",
      "Speech pattern recognition and coaching",
      "Social communication scenario practice",
    ],
    img: "/images/tutors/echo.png",
  },
  {
    name: "Harmony",
    domain: "Social-Emotional Learning",
    color: "#8B5CF6",
    bg: "from-violet-400 to-purple-500",
    tagline: "Feelings are superpowers when you understand them.",
    bullets: [
      "Emotion recognition and regulation tools",
      "Guided mindfulness and calming exercises",
      "Social scenario role-playing and reflection",
    ],
    img: "/images/tutors/harmony.png",
  },
  {
    name: "Atlas",
    domain: "Geography & World Studies",
    color: "#14B8A6",
    bg: "from-teal-500 to-emerald-600",
    tagline: "Explore every corner of the world.",
    bullets: [
      "Interactive map-based learning journeys",
      "Cultural exploration and global awareness",
      "Climate, ecology, and human geography",
    ],
    img: "/images/tutors/atlas.png",
  },
  {
    name: "Cadence",
    domain: "Music & Rhythm",
    color: "#D946EF",
    bg: "from-fuchsia-500 to-pink-600",
    tagline: "Every learner has a rhythm inside.",
    bullets: [
      "Rhythm and beat pattern recognition",
      "Music theory through playful composition",
      "Sensory-friendly audio experiences",
    ],
    img: "/images/tutors/cadence.png",
  },
  {
    name: "Vigor",
    domain: "Physical Education & Wellness",
    color: "#22C55E",
    bg: "from-green-500 to-lime-600",
    tagline: "Move, play, and grow stronger.",
    bullets: [
      "Adaptive movement and exercise routines",
      "Motor skills development activities",
      "Health and wellness habit building",
    ],
    img: "/images/tutors/vigor.png",
  },
  {
    name: "Lingua",
    domain: "World Languages",
    color: "#EF4444",
    bg: "from-red-500 to-rose-600",
    tagline: "Open doors with every new word.",
    bullets: [
      "Immersive language learning environments",
      "Speech recognition and pronunciation practice",
      "Cultural context integrated into every lesson",
    ],
    img: "/images/tutors/lingua.png",
  },
  {
    name: "Forge",
    domain: "STEM & Engineering",
    color: "#92400E",
    bg: "from-amber-700 to-yellow-800",
    tagline: "Design, build, and engineer the future.",
    bullets: [
      "Hands-on engineering design challenges",
      "Iterative prototyping and testing cycles",
      "Math, science, and technology integration",
    ],
    img: "/images/tutors/forge.png",
  },
  {
    name: "Compass",
    domain: "Executive Function & Life Skills",
    color: "#1E40AF",
    bg: "from-blue-700 to-indigo-800",
    tagline: "Navigate life with confidence.",
    bullets: [
      "Time management and planning practice",
      "Decision-making and problem-solving skills",
      "Self-advocacy and independence building",
    ],
    img: "/images/tutors/compass.png",
  },
  {
    name: "Muse",
    domain: "Creative Arts & Expression",
    color: "#A855F7",
    bg: "from-purple-500 to-fuchsia-600",
    tagline: "Create without limits.",
    bullets: [
      "Digital art tools and guided drawing",
      "Creative expression across mediums",
      "Art history and appreciation adventures",
    ],
    img: "/images/tutors/muse.png",
  },
];
