"use client";
import { LegalPageLayout } from "@/components/marketing/legal/LegalPageLayout";

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      badge="Legal"
      title="Privacy Policy"
      subtitle="AIVO is built for learners with diverse needs — including children. Protecting their privacy is one of our highest priorities. This policy explains, in plain language, what we collect, how we use it, and the choices you have."
      icon="🔒"
      accentColor="#7c3aed"
      lastUpdated="December 15, 2026"
      contactEmail="privacy@aivo.education"
      sections={[
        {
          title: "Our Privacy Principles",
          content: "Before the legal detail, here is what we promise:",
          list: [
            "We never sell personal information to anyone, ever.",
            "We do not show third-party advertising to learners or use learner data to target ads.",
            "We do not use identifiable learner data to train third-party AI foundation models.",
            "We collect only what we need to provide the Services and improve them for you.",
            "We give you meaningful access to and control over your information, and the same for your child's information.",
            "We apply extra protections to data about children, students, and learners on IEPs.",
          ],
        },
        {
          title: "Who This Policy Applies To",
          content: [
            "AIVO Learning, Inc. (\"AIVO\", \"we\", \"us\", \"our\") is a U.S. company that operates the AIVO Learning Platform — our website, mobile apps, and online services (the \"Services\"). This Privacy Policy explains how we collect, use, and disclose personal information when you use the Services.",
            "Different rules can apply depending on who you are. Where the Services are used in a school setting, our COPPA Compliance Notice and FERPA Compliance Notice supplement this Policy. If a separate agreement exists between AIVO and a school or district, that agreement controls in case of conflict for student data.",
          ],
        },
        {
          title: "Information We Collect",
          content: "We collect information in three main ways:",
          list: [
            "Information you give us directly — for example when you register, set up a learner profile, complete an IEP intake, contact support, or pay for a subscription. This may include names, email addresses, parent/guardian relationship, learner age, grade level, learning preferences, and (for paid plans) billing information processed by our payment processor.",
            "Information generated by use of the Services — for example lesson responses, time on task, mastery signals, AI-tutor conversations, voice or audio recordings (where features like read-aloud or speech are enabled), Brain-Clone learning model attributes, and progress events used to power personalization and reports.",
            "Information collected automatically — for example device type, operating system, browser, IP address, approximate location derived from IP, language settings, crash logs, and similar technical telemetry. We use cookies and similar technologies as described in our Cookie Policy.",
          ],
        },
        {
          title: "How We Use Information",
          content: "We use personal information only for legitimate, education-focused purposes:",
          list: [
            "To provide and operate the Services, including authenticating users and personalizing each learner's experience.",
            "To power Brain-Clone and our AI tutors so that lessons adapt to a learner's strengths, preferences, and IEP goals.",
            "To generate progress reports, parent dashboards, and (for District Plans) educator and admin reports.",
            "To communicate with parents, educators, and account holders about their account, support requests, and important Service updates.",
            "To keep the Services secure, prevent fraud and abuse, and comply with our legal obligations.",
            "To research and improve the Services, using de-identified or aggregated data wherever possible.",
            "To send marketing or product update emails to adults only — never to learners — and only where the recipient has opted in or has an existing relationship with us. You can unsubscribe at any time.",
          ],
        },
        {
          title: "How We Share Information",
          content: "We do not sell personal information. We share it only in these limited circumstances:",
          list: [
            "With service providers acting on our behalf — for example cloud hosting, email delivery, error monitoring, and payment processing — under contracts that require them to protect your information and use it only for the services we ask them to perform.",
            "With AI model providers solely to generate tutor responses for the Services. We use enterprise contracts that prohibit providers from using inputs or outputs to train their underlying models, and we instruct users not to include unnecessary personal information in AI prompts.",
            "With parents, guardians, or schools that legitimately oversee a learner's account.",
            "With other users when you explicitly choose to share something — for example sending a progress report.",
            "For legal reasons — to comply with a valid legal request, to protect the rights, safety, or security of AIVO, our users, or the public, or in the context of a merger, acquisition, or sale of assets, in which case we will require the recipient to honor commitments at least as protective as this Policy.",
          ],
        },
        {
          title: "Children's Privacy (COPPA)",
          content: [
            "AIVO is intended for use by children with the involvement of a parent, guardian, or school. We comply with the Children's Online Privacy Protection Act (\"COPPA\") and similar laws.",
            "When a child under 13 uses the Services in a personal account, we obtain verifiable parental consent before collecting personal information. When the Services are used in a school under a District Plan, the school may provide consent on behalf of parents to the extent permitted by COPPA's school-authorization exception, and the institution is responsible for any additional notices or consents required by state law.",
            "Parents and schools can review, modify, or delete a child's information at any time. See our COPPA Compliance Notice for full detail.",
          ],
        },
        {
          title: "Schools, Students, and Education Records (FERPA)",
          content: [
            "When AIVO is used in a U.S. school under a District Plan, student information may constitute an education record under the Family Educational Rights and Privacy Act (\"FERPA\"). In that role, AIVO acts as a school official with a legitimate educational interest, under the direction and control of the school.",
            "Education records remain owned and controlled by the school or district. We use student personal data only to provide the Services to the school, never for advertising, never for sale, and never to train external AI models. See our FERPA Compliance Notice for full detail.",
          ],
        },
        {
          title: "Your Choices and Rights",
          content: "You have meaningful control over your information:",
          list: [
            "Access and correction — review and update profile, learner, and billing information from your account dashboard.",
            "Deletion — delete your account, or your child's learner profile, from the dashboard or by emailing privacy@aivo.education. We will delete or de-identify the associated data unless we are required to retain it for legal or security reasons.",
            "Data export — request a portable copy of your account and learner data.",
            "Communication preferences — opt out of marketing emails using the unsubscribe link in any message; transactional emails about your account or subscription are not optional.",
            "Cookie controls — manage cookie preferences through our Cookie Policy and your browser settings.",
            "Regional rights — depending on where you live, you may have additional rights under laws such as the GDPR (EU/UK), the CCPA/CPRA (California), and similar state and national laws. To exercise those rights, contact privacy@aivo.education and identify the right you wish to exercise.",
          ],
        },
        {
          title: "Data Security",
          content: [
            "We use reasonable administrative, technical, and physical safeguards designed to protect personal information against loss, misuse, and unauthorized access. Personal information is encrypted in transit (TLS) and at rest, access is limited to staff who need it to perform their roles, and we monitor for security events.",
            "No system is perfectly secure, so we also encourage strong, unique passwords for every account and prompt reporting of any suspicious activity to security@aivo.education.",
          ],
        },
        {
          title: "Data Retention",
          content: "We keep personal information only for as long as needed to provide the Services and to comply with our legal obligations. When a learner profile or account is deleted, we delete or de-identify the associated personal information within a reasonable period, except where retention is required for legal, accounting, security, or fraud-prevention purposes. De-identified or aggregated data, which cannot reasonably be linked back to a person, may be kept longer for research, analytics, and Service improvement.",
        },
        {
          title: "International Users",
          content: [
            "AIVO is operated from the United States, and our hosting infrastructure is primarily located in the United States. If you access the Services from outside the U.S., you understand that your information will be processed in the U.S. and other countries that may have data-protection laws different from those in your jurisdiction.",
            "Where required by law (for example for users in the European Economic Area or the United Kingdom), we rely on appropriate transfer mechanisms such as the Standard Contractual Clauses to protect personal information when it leaves your region.",
          ],
        },
        {
          title: "Changes to This Privacy Policy",
          content: "We may update this Privacy Policy from time to time. If we make material changes, we will let you know — for example by emailing the address on file or posting a prominent notice on the Services — before the changes take effect. We will not make material changes to how student personal data is collected or used without first giving the school notice and a meaningful choice.",
        },
        {
          title: "How to Contact Us",
          content: "Questions, requests, or concerns about this Privacy Policy or your personal information are welcome. Email our privacy team at privacy@aivo.education. For school and district matters, email compliance@aivo.education. For security reports, email security@aivo.education.",
        },
      ]}
    />
  );
}
