"use client";
import { LegalPageLayout } from "@/components/marketing/legal/LegalPageLayout";

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout
      badge="Legal"
      title="AIVO Terms of Service"
      subtitle={
        "Welcome! We're glad you're interested in Aivo AI Learning Technologies Inc., a U.S. company that builds adaptive learning for neurodivergent learners. We own and operate the website at aivolearning.com, our mobile apps, our APIs, and any other products or services we may offer now or in the future. Together, we call all these our \"Services.\" You're entering into a legal agreement with us, AIVO, when you use our Services. Whether you're just visiting our sites or actively using our Services, we'll refer to you as a \"User\" or collectively as \"Users.\" These Terms of Service, together with our Privacy Policy, Cookie Policy, COPPA Compliance Notice, FERPA Compliance Notice, and any additional Guidelines (collectively, the \"Terms\"), set the rules for your use of our Services. PLEASE READ THESE TERMS CAREFULLY. BY REGISTERING FOR, ACCESSING, BROWSING, OR USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. THESE TERMS INCLUDE A BINDING ARBITRATION PROVISION AND A CLASS ACTION WAIVER."
      }
      icon="📜"
      accentColor="#2563eb"
      lastUpdated="December 15, 2026"
      contactEmail="legal@aivolearning.com"
      sections={[
        {
          title: "1. Eligibility",
          content: [
            "Access to our Services may be subject to restrictions based on the User's age and location, and certain features are limited to specific types of Users. By selecting a specific account type or feature, you confirm that you meet any applicable eligibility criteria. You are responsible for complying with the terms relevant to the account type and related features.",
            "THE SERVICES ARE NOT AVAILABLE TO: (A) ANY USERS PREVIOUSLY SUSPENDED OR REMOVED FROM THE SERVICES BY AIVO, OR (B) ANY PERSONS UNDER THE AGE OF 13 (OR UNDER THE LEGAL AGE OF CONSENT IN YOUR COUNTRY) WHOSE REGISTRATION HAS NOT BEEN APPROVED BY A PARENT (OR, FOR SCHOOL ACCOUNTS, BY SCHOOL PERSONNEL AS PERMITTED UNDER THE TERMS).",
            "1.1. Acceptance. By clicking the \"Sign Up,\" \"I Agree,\" or similarly labeled button, or by otherwise using or registering an account for the Services, you represent that (i) you are a U.S. resident at least 13 years of age, or (ii) you are not a U.S. resident and are of legal age of consent to open an account under the laws of your country of residence, or (iii) your use of the Services has been approved by your Parent, or by your school or teacher for school use (as explained in Section 3 (School Use)). You also represent that you have not been previously suspended or removed from the Services by AIVO and that your registration and your use of the Services is in compliance with all applicable laws.",
          ],
        },
        {
          title: "2. User Accounts",
          content: [
            "AIVO offers website accounts designed for learners, parents, and teachers. This section includes terms relevant to specific account types made available to specific Users.",
            "2.1. User Account Terms. User accounts and use of the standard features of the Services are governed exclusively by these Terms and the applicable Privacy Policy. To use certain features, you must register for an account. You are solely responsible for maintaining the confidentiality of your account and password, and you agree to accept responsibility for all activities that occur under your account. You agree that the information you provide to AIVO will be true, accurate, current, and complete, and that you will keep it up to date. If you have reason to believe that your account is no longer secure, you agree to immediately notify us at security@aivolearning.com. You may be liable for losses incurred by AIVO or others due to any unauthorized use of your account.",
            "2.2. Learner Accounts; Child Users. Any User may register for an account as a learner. If you are under the age of 13 in the United States, or under the legal age of consent in your country, then you are a \"Child User,\" and you may not create an account for the Services without consent and approval from your Parent, or from your school as explained in Section 3 (School Use). If you are under the age of 18 (or under the legal age of majority in your country), you represent that your Parent has reviewed and agreed to the Terms on your behalf.",
            "2.3. Parent Accounts. If you are at least 18 years of age and you are the Parent of a child that seeks to register as a Child User of the Services, you may register for a parent account (\"Parent User\"). For the purposes of these Terms, \"parental consent\" refers to a Parent providing consent for their Child User. Through a Parent User account, you may create, register, manage, and approve Child User accounts only for your own child(ren) or child(ren) for whom you are a legal guardian. IF YOU REGISTER, APPROVE, OR CONSENT TO THE REGISTRATION OF, OR OTHERWISE ASSUME RESPONSIBILITY FOR ANY CHILD USER, YOU REPRESENT AND WARRANT THAT YOU ARE SUCH CHILD USER'S PARENT AND YOU AGREE TO BE BOUND BY THE TERMS ON BEHALF OF SUCH CHILD USER.",
            "2.4. Teacher Accounts. The Services include certain features and tools designed for use by teachers. Persons over the age of 18 (or the age of majority in the jurisdiction in which you reside) who are employed in an official capacity as a school teacher (or other School Personnel as defined below) may register for a teacher account. Brain-Clone Teacher Tools and other AI-Enabled Features designed specifically for School Personnel are made available subject to geographic and school-based restrictions. By signing up for a teacher account, you represent that you meet the foregoing eligibility criteria and that your use of AI-Enabled Features is permitted by your school's policies.",
          ],
        },
        {
          title: "3. School Use",
          content: [
            "AIVO may make available certain features and tools designed for use by teachers, school leaders, aides, principals, school administrators, school district administrators, or other similar school personnel (\"School Personnel\"), including productivity tools and features that enable School Personnel to work with Students through the Services. If you are School Personnel accessing the Services on behalf of a school, school district, or other similar educational institution (an \"Institution\"), the following terms apply to you:",
            "3.1. Limitations on Use. The Services are provided to you for educational purposes as part of the school curriculum. You must use the Services in compliance with all applicable laws, rules, and regulations. You are responsible for determining (and confirming) that your use of the Services is permitted by your Institution and any applicable policies. You acknowledge that our Services are provided as an educational aid and not as a substitute for your professional judgment in assessing student performance.",
            "3.2. Responsibility for Consent and Notices. You and/or the Institution assume responsibility for obtaining any consents required from Parents, and for providing appropriate disclosures to Student Users and their Parents regarding Student use of the Services, our Terms, and our Privacy Policy. IF YOU ARE SCHOOL PERSONNEL AND YOU REGISTER AN ACCOUNT FOR A CHILD USER OR OTHER STUDENT FOR SCHOOL USE (EACH, A \"STUDENT\" OR \"STUDENT USER\"), YOU REPRESENT AND WARRANT THAT YOU HAVE EITHER RECEIVED EXPRESS CONSENT FROM SUCH STUDENT USER'S PARENT OR THAT YOU (OR YOUR INSTITUTION) HAVE COMPLIED WITH ALL APPLICABLE REQUIREMENTS OF AN EXEMPTION FROM PARENTAL CONSENT REQUIREMENTS.",
            "3.2.1. Compliance with U.S. Laws. If you are using our Services for School Use in the United States, you agree, individually and on behalf of your Institution, that: (i) you shall comply with and provide any notices and obtain any consent required under the Family Educational Rights and Privacy Act and the U.S. Department of Education's implementing regulations at 34 CFR Part 99 (collectively, \"FERPA\"), the Children's Online Privacy Protection Act of 1998, as amended (\"COPPA\"), and all other applicable laws, rules, or regulations concerning the collection, use, and disclosure of personally identifiable information (collectively, \"Applicable Privacy Law\"); and (ii) you will remain responsible for complying with all parental notice requirements and parental requests (\"School Consent\"). If a Parent does not consent or rescinds School Consent, School Personnel or the Institution shall immediately notify AIVO to discontinue that Student's access.",
            "3.3. School Accounts. Students and School Personnel may have personal accounts in addition to accounts established for use in the classroom and associated with the Institution's use of the Services (\"School Accounts\"). Accounts may be designated as School Accounts when (1) created by School Personnel, including via Google Classroom, Clever, ClassLink, or similar Integrated Service, or (2) created by a Student User at the direction of School Personnel, in each case using a school email address and associated with a school's class on the Service. The Institution is solely responsible for the accuracy of roster data.",
            "3.4. Institutional Services. AIVO may enter into supplemental written agreements with school districts or similar education agencies with respect to use of the Services on a district-wide basis (\"District Agreements\"). Except as otherwise provided in a District Agreement, these Terms remain in effect for all individual Users of the Services in the relevant district.",
          ],
        },
        {
          title: "4. International Use",
          content: [
            "This section includes additional terms that apply to Users that habitually reside outside the United States of America. Certain content or features may not be available in all regions, or may be available in the English language only.",
            "4.1. Compliance with Law. You agree to comply with and are solely responsible for ensuring compliance with all local laws, regulations, and rules in the jurisdiction in which you reside or access the Services. Where Parent consent is required (including but not limited to use within an Institution), it must be provided by a Parent or other person authorized to provide parental consent under the laws of your jurisdiction. We do not represent that our Services are appropriate or available for use in jurisdictions outside the United States.",
            "4.2. Location of Data Processing. AIVO operates the Services in the United States. If you access our Services from outside the United States, you acknowledge and agree that your information, including your personal information and user-generated content, will be collected, transferred, stored, and processed in the United States, where data protection laws may differ from those in your jurisdiction. This transfer is necessary to provide the Services to you in accordance with our Terms.",
            "4.3. Additional Consumer Rights May Apply. If you habitually reside outside the United States of America, you may have additional or different rights under applicable laws. Where mandatory statutory consumer protections in your country of residence are more beneficial for you, those statutory protections shall apply, irrespective of the choice of Delaware law in our Terms or any conflicting provision herein. To the extent required by applicable law, the binding arbitration clause of our Terms will not apply to you, and any proceeding to enforce these Terms against you as a consumer must be brought in the courts of your jurisdiction of habitual residence.",
            "4.4. Export Compliance; Geographic Restrictions. You agree that you will not use, export, re-export, or re-transfer the Services except as authorized by the laws and regulations of the United States and any other applicable jurisdiction. The Services may not be exported to any jurisdiction subject to comprehensive U.S. economic sanctions or to any person on a U.S. government restricted-party list. You agree not to use VPNs, proxy servers, or other circumvention tools to mask your location or evade any geographic, technical, or access restrictions we have implemented.",
          ],
        },
        {
          title: "5. Privacy Policy; Supplemental Terms and Guidelines",
          content: [
            "5.1. Privacy Policy. Your privacy is important to AIVO. Please read the AIVO Privacy Policy, COPPA Compliance Notice, and FERPA Compliance Notice carefully for information relating to AIVO's collection, use, and disclosure of your personal information. Among other things, our Privacy Policy explains how we treat your personal information and protect your privacy when you use our Services, and explains the procedures by which Users, Parent Users, and School Personnel may view, update, correct, or delete their account and personal information.",
            "5.2. Supplemental Terms. In addition to these Terms, we may offer paid services or special programs or features which are subject to supplemental terms, which apply in addition to these Terms and take precedence over these Terms in the event of a conflict. Certain features may be available by subscription only, subject to additional terms of purchase. Subscription tiers currently include the Free Plan (limited access for one learner, English Language Arts content only), the Single Learner Plan ($24.99 per month per learner), the Family Plan ($19.99 per month per learner), and District Plans (custom pricing under a separate written agreement). Subscriptions renew automatically and may be canceled at any time from your account dashboard.",
            "5.3. Guidelines. When using the Services, you will be subject to any additional posted guidelines or rules applicable to specific Services and features which may be posted from time to time (the \"Guidelines\"). All such Guidelines are hereby incorporated by reference into the Terms. You and your use of the Services must comply at all times with these Terms.",
          ],
        },
        {
          title: "6. User Content; License Grant",
          content: [
            "6.1. User Content and Ownership. The Services include features that allow Users to (a) post and/or publish questions, comments, notes, ratings, reviews, images, audio recordings, and other communications (collectively, \"User Postings\"), (b) create or modify computer code (\"User Code\"), and (c) provide input to AI-Enabled Features (\"Input\") and receive output generated by the AI-Enabled Feature based on the Input (\"Output\"). Input and Output together constitute \"AI Content\" (together with User Postings and User Code, \"User Content\"). Consistent with Applicable Law, as between AIVO and you, you retain all ownership rights you have in any User Content you post or publish to the Services, and AIVO does not claim any ownership rights in such User Content.",
            "6.2. License Grant to AIVO. By posting, submitting, or distributing User Content on or through the Services, you hereby grant to AIVO a worldwide, non-exclusive, transferable, assignable, fully paid-up, sublicensable, royalty-free right and license to host, transfer, display, reproduce, and use your User Content, in whole or in part, in any media formats and through any media channels, to the extent consistent with Applicable Law and AIVO's Privacy Policy. With respect to School Accounts, consistent with Applicable Privacy Law, you (or your school, as applicable) retain all ownership rights you have in any User Content to the extent such content is an education record. By using AI-Enabled Features, you grant us a license to access, use, and process Inputs and Outputs solely to provide our Services to you and to evaluate and improve our Services in accordance with Applicable Law and our Privacy Policy. We never use identifiable learner data to train third-party AI foundation models.",
            "6.3. License Grant to Users. By posting User Postings through the Services, you grant each User of the Services a non-exclusive license to access and use your User Postings in any manner permitted or made available by AIVO. The Services may permit you to download mobile applications or certain digital educational content (\"Downloadable Content\"), under a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to use the Downloadable Content, in object code form, on devices owned or controlled by you, solely for your personal, non-commercial purposes.",
            "6.4. Access to Your User Content. AIVO may permit Users to share their User Content with a select group of other Users, or make certain User Content public for all to view. Although AIVO provides features intended to allow you to restrict some User Content from others, AIVO does not guarantee that such User Content will never be accessible by others. AIVO HEREBY DISCLAIMS ANY AND ALL LIABILITY WITH RESPECT TO ANY UNAUTHORIZED ACCESS TO ANY RESTRICTED USER CONTENT.",
            "6.5. User Content Disclaimer. You understand that when using the Services you may be exposed to User Content from a variety of sources, and that AIVO is not responsible for the accuracy, usefulness, or intellectual property rights of such User Content. AIVO does not endorse any User Content and expressly disclaims any and all liability in connection with User Content.",
            "6.6. Feedback. We welcome your feedback on our Services. By submitting suggestions or other feedback, you agree that we can (but do not have to) use and share such feedback for any purpose without compensation to you. You grant us a royalty-free, worldwide, irrevocable, perpetual license to use and incorporate your feedback into our Services or to develop new features and services.",
          ],
        },
        {
          title: "7. Digital Millennium Copyright Act",
          content: "It is AIVO's policy to respond to notices of alleged copyright infringement that comply with the Digital Millennium Copyright Act. To submit a DMCA notice, please email legal@aivolearning.com with the information required under 17 U.S.C. § 512(c)(3). AIVO will promptly terminate without notice your access to the Services if you are determined by AIVO to be a \"repeat infringer.\" A repeat infringer is a User who has been notified by AIVO of infringing activity violations more than twice and/or who has had User Content removed from the Services more than twice.",
        },
        {
          title: "8. Proprietary Materials; Licenses",
          content: [
            "8.1. Proprietary Materials. The Services are owned and operated by Aivo AI Learning Technologies Inc. The visual interfaces, graphics, design, compilation, information, computer code, software, services, content, educational videos and exercises, Brain-Clone learning models, training materials, and all other elements of the Services (the \"Services Materials\") are protected by United States and international laws governing intellectual property and proprietary rights. All Services Materials, and all trademarks, service marks, and trade names contained on or available through the Services, are owned by or licensed to AIVO, and AIVO reserves all rights therein and thereto not expressly granted by these Terms.",
            "8.2. Access to Evaluation Services. AIVO may offer pilot programs (each a \"Pilot\") or permit you to access pre-release Services that are under development, prototype, or experimental features (\"Betas\") (collectively, \"Evaluation Services\"). YOU ACKNOWLEDGE AND AGREE THAT EVALUATION SERVICES MAY FUNCTION FOR A LIMITED PERIOD OF TIME, HAVE LIMITED FEATURES, MAY MAKE ERRORS, AND HAVE OTHER LIMITATIONS. AIVO IS PROVIDING EVALUATION SERVICES \"AS IS,\" AND AIVO DISCLAIMS ANY AND ALL WARRANTIES INCLUDING ANY IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, AND STATUTORY WARRANTIES OF NON-INFRINGEMENT.",
            "8.3. Licensed Educational Content. AIVO may make available on the Services certain educational videos, exercises, and related supplementary materials that are owned by AIVO or its third-party licensors (the \"Licensed Educational Content\"). AIVO grants to you a non-exclusive, non-transferable right to access and use the Licensed Educational Content as made available on the Services solely for your personal, non-commercial purposes (or, for District Plans, for the institution's educational use). You may not download, distribute, sell, lease, modify, or otherwise provide access to the Licensed Educational Content to any third party.",
            "8.4. Non-Commercial Use. The Licensed Educational Content is intended for personal, non-commercial use only and may not be used, distributed, or otherwise exploited for any commercial purpose, commercial advantage, or private monetary compensation, unless otherwise previously agreed in writing by AIVO. By way of example, the sale or rental of the Licensed Educational Content, charging fees for training that uses the Licensed Educational Content, or selling advertisements placed on the Licensed Educational Content are not permitted.",
          ],
        },
        {
          title: "9. Prohibited Conduct",
          content: "YOU AGREE NOT TO use any portion of the Services or access to the Services (including AI-Enabled Features) for any of the following:",
          list: [
            "for any commercial use or purpose unless expressly permitted by AIVO in writing; the Services are intended for personal, non-commercial use only (or for educational use under a District Agreement);",
            "to post, upload, generate, promote, or distribute any User Content or other content that is unlawful, defamatory, libelous, or invasive of another's privacy, or that a reasonable person could deem objectionable, including content that is hateful, harassing, threatening, sexually explicit, or promotes violence or self-harm;",
            "to post, upload, generate, promote, or distribute any content that contains malware or is designed to damage, disrupt, or gain unauthorized access to any system, device, or data, or to reproduce, duplicate, copy, sell, resell, or otherwise exploit the Services;",
            "to use any software, technology, or other means or processes to scrape the Services or otherwise copy materials or other data from the Services, or use any content, data, output, or other information available from our site to develop, train, fine-tune, test, align, or otherwise improve any machine learning algorithms or artificial intelligence models;",
            "use of the Services in any manner that is harmful to minors, or in any manner that violates AIVO's Community Guidelines;",
            "use of the Services to commit any act of educational or academic dishonesty, or to engage in any other conduct that violates AIVO's Prohibited Conduct Guidelines, which are incorporated herein by reference and may be updated from time to time.",
          ],
        },
        {
          title: "10. Specific Account Functionality; AI-Enabled Features",
          content: [
            "This section includes additional terms relevant to specific features or account functionality. Certain features and services may be limited by geographic restrictions and to Users who meet specific eligibility criteria.",
            "10.1. Integrated Service. AIVO may permit you to register for the Services through, or otherwise associate your AIVO account with, certain third-party social networking or integrated services such as Google, Clever, or ClassLink (\"Integrated Service\"). By registering for the Services using (or otherwise granting access to) an Integrated Service, you agree that AIVO may access your Integrated Service's account information consistent with our Privacy Policy, and you agree to any and all terms and conditions of the Integrated Service. You should check your account settings on each Integrated Service to understand the information sent to us.",
            "10.2. Linked Accounts. AIVO may permit a User to associate a personal account with their School Account. If a User chooses to associate a personal account with their School Account, the two accounts will be deemed \"Linked\" Accounts, and the User's learning activity, whether generated during or outside of the school use, may be viewed by any person with access to either account. Linked Accounts may benefit Students who want to use the Services for both personal and school purposes. Once accounts are linked, they cannot be separated.",
            "10.3. AI-Enabled Features; Brain-Clone. AIVO offers certain artificial intelligence-enabled features, technologies, and services, including \"Brain-Clone,\" our adaptive learning engine that builds a private cognitive model for each learner; AI tutors; and additional AI-enabled features that may be included in the Services (collectively, \"AI-Enabled Features\").",
            "10.3.1. AI-Enabled Features Subject to Change. AI-Enabled Features use new artificial intelligence technologies that are at an early stage of development, are known to make errors and to provide incorrect information at times, and may have other bugs. AIVO may change, add, or remove specific AI-enabled tools, features, elements, or portions thereof at any time without any liability to you, and we do not commit to maintaining any AI-Enabled Feature.",
            "10.3.2. User-Generated Content. You may provide Input to any AI-Enabled Feature and receive Output. Input and Output are collectively \"AI Content\" and constitute User Content under these Terms. You are solely responsible for the Input that you and your authorized Users provide and for the use of Output. You and your authorized Users are responsible for conducting human review of Outputs and double-checking Outputs with reputable sources to confirm that such Outputs are accurate, lawful, and otherwise appropriate before relying on them. AIVO reserves the right to determine whether any AI Content violates our Prohibited Conduct terms, and may refuse, remove, or edit such AI Content.",
            "10.3.3. School Use. School Personnel should apply their judgment and discretion, and their school's policies regarding use of AI, in use of all AI-Enabled Features. AI-Enabled Features are not intended as a substitute for human judgment in performance evaluations or IEP decisions. School Personnel should not rely solely (nor predominantly) on AI-Enabled Features to make consequential decisions about a Student or School Personnel.",
            "10.3.4. Supervising Child and Student Use. Any use of AI-Enabled Features by persons under age 18 must be supervised by an authorized adult User (their Parent, teacher, or other School Personnel). Each account held by a Student or minor with access to AI-Enabled Features must be associated with an account held by an authorized teacher or other School Personnel (in the case of School Accounts) or by a Parent (in the case of personal accounts).",
            "10.3.5. Privacy Guidance. AI-Enabled Features enable Users to interact with one or more large language models (\"LLMs\") developed and maintained by third-party model providers. AI-Enabled Features are not intended to be used to process proprietary or personally identifiable information beyond what is required to deliver the Service. YOU ARE ADVISED NOT TO (AND YOU MUST INSTRUCT YOUR AUTHORIZED USERS NOT TO) INCLUDE ANY PROPRIETARY OR PERSONALLY IDENTIFIABLE INFORMATION IN INPUTS SUBMITTED TO ANY AI-ENABLED FEATURE BEYOND WHAT IS REASONABLY NECESSARY FOR YOUR INTENDED USE.",
          ],
        },
        {
          title: "11. Third Party Sites, Products and Services; Links",
          content: "The Services may include links or references to other websites or services solely as a convenience to Users (\"Reference Sites\"). AIVO does not endorse any such Reference Sites or the information, materials, products, or services contained on or accessible through Reference Sites. The Services may include access to third-party platforms, apps, add-ons, services, or products (\"Third-Party Products\"). Use of Reference Sites and Third-Party Products is subject to the relevant provider's terms and conditions and not this Agreement. ACCESS AND USE OF REFERENCE SITES AND THIRD-PARTY PRODUCTS IS SOLELY AT YOUR OWN RISK. Certain AIVO features and services, including certain AI-Enabled Features, rely on the continued availability and functionality of independently operated third-party services, platforms, and APIs (\"Third-Party Dependencies\"). AIVO makes no representations, warranties, or guarantees regarding the continued availability of any Third-Party Dependencies, and AIVO may, without liability, suspend or discontinue any Dependent Feature if access to the relevant Third-Party Dependencies cannot be restored.",
        },
        {
          title: "12. Modification of the Terms",
          content: [
            "12.1. General. Upon opening an account, you accept the Terms in the form posted on our website. AIVO reserves the right to change, modify, add, or remove portions of the Terms at any time. Please check the Terms and any Guidelines periodically for changes. Your continued use of the Services after the posting of changes constitutes your binding acceptance of such changes. For any material changes to the Terms, AIVO will make reasonable effort to provide notice to you, such as by an email notification to the address associated with your account or by posting a notice on the website, and such amended terms will be effective against you on the earlier of (i) your actual notice of such changes and (ii) thirty days after AIVO makes reasonable attempt to provide you such notice. However, changes addressing new functions for a service or changes made for legal reasons will be effective immediately. If you do not agree to the modified Terms, you must discontinue your use of the Services.",
            "12.2. School Accounts. If a change with respect to how personal information contained in education records is used or shared has a material adverse impact on Student Users or an Institution, and the Institution does not agree to the change, the Institution must notify AIVO within thirty days of receiving the notice of change. If AIVO is so notified, the School Accounts held by that Institution will remain governed by the Terms in effect immediately prior to the change until the end of the then-current term of the Institution's written service agreement with AIVO, or, in the absence of such an agreement, the end of the current school term.",
          ],
        },
        {
          title: "13. Term and Termination",
          content: [
            "13.1. Term. These Terms shall remain in full force and effect while you use the Services unless your account is terminated as provided in these Terms.",
            "13.2. Termination by AIVO. We reserve the right to terminate or change any of our Services as circumstances may warrant to the full extent permitted by applicable law. If we determine that you are using the Services in a manner that is not in compliance with these Terms, AIVO may: (a) restrict, suspend, or terminate any account (or any part thereof) you may have with AIVO or your use of the Services, and (b) remove and discard all or any part of your account, User profile, and User Content. To the full extent permitted by law, any termination may be effected without prior notice, and AIVO will not be liable to you or any third party for any such termination. Any suspected fraudulent, abusive, or illegal activity may be referred to appropriate law enforcement authorities. If we determine that your AIVO account is inactive, we may delete the account in accordance with our inactive account policy.",
            "13.3. Termination by You. Your only remedy with respect to any dissatisfaction with the Services or any term of these Terms is to terminate the Terms and your account. You may terminate these Terms at any time (prospectively only) by deleting your account with the Services and discontinuing use of any and all parts of the Services.",
            "13.4. Termination of School Personnel, Child and Student Accounts. School Personnel may terminate use of the Services individually and/or with respect to School Accounts created by such School Personnel at any time by contacting compliance@aivolearning.com, provided that an Institution may require satisfaction of certain requirements before School Personnel can terminate accounts created for school use. As a Parent User, you can terminate your Child User's account through the account profile, or by contacting our support team, although we may need to verify your identity prior to taking any action with respect to the account.",
            "13.5. Responsibility for Pre-Termination Activity. Termination of the Terms as to any User account will not limit AIVO's rights and remedies regarding any breach of these Terms occurring prior to such termination.",
          ],
        },
        {
          title: "14. Representations and Warranties",
          content: "You warrant, represent, and agree that you will not provide any User Content or otherwise use the Services in a manner that (i) infringes, violates, or misappropriates another's intellectual property rights, rights of publicity or privacy, or other rights; (ii) violates any international, federal, state, or local law, statute, ordinance, or regulation, including without limitation Applicable Privacy Laws (collectively, \"Applicable Law\"); (iii) is harmful, fraudulent, threatening, abusive, harassing, defamatory, vulgar, obscene, libelous, or otherwise Prohibited Conduct as defined in Section 9; or (iv) jeopardizes the security of your account or the Services. Additionally, you represent and warrant that (i) you possess all rights necessary to provide your User Content and grant AIVO the rights in these Terms; (ii) you will comply with Applicable Laws in connection with your use of the Services; and (iii) if you are School Personnel, you understand that you are responsible for providing notices and obtaining consents required by Applicable Laws, including, for U.S. schools, compliance with FERPA and COPPA when using School Consent.",
        },
        {
          title: "15. Indemnification",
          content: "To the extent permitted by applicable law, you will indemnify, defend, and hold harmless AIVO and its parent, successors, affiliated companies, contractors, officers, directors, employees, agents, and its third-party suppliers, licensors, and partners (collectively, the \"AIVO Parties\") from and against all losses, damages, liabilities, demands, judgments, settlements, costs, and expenses of any kind (including legal fees and expenses), from any claim or demand made by any third party relating to or arising out of (i) your access to and use of the Services not fully in accordance with these Terms; (ii) your failure to comply with Applicable Laws in connection with your use of the Services (including any failure to obtain or provide any required consent or notice); and (iii) your User Content, including the infringement by you or any third party using your account of any intellectual property right of any person or entity. AIVO reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify AIVO. You agree not to settle any such matter without the prior written consent of AIVO.",
        },
        {
          title: "16. Warranty Disclaimers",
          content: [
            "16.1. Warranty Disclaimers. THE SERVICES, WEBSITE, AND ANY ASSOCIATED CONTENT, THIRD-PARTY CONTENT, THIRD-PARTY WEBSITES, THIRD-PARTY APPLICATIONS, USER CONTENT, AND ALL DATA AND INFORMATION MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE WEBSITE OR SERVICES (COLLECTIVELY, THE \"AIVO OFFERINGS\"), ARE PROVIDED ON AN \"AS IS,\" \"AS AVAILABLE,\" AND \"WITH ALL FAULTS\" BASIS. THE AIVO PARTIES DO NOT WARRANT THAT THE AIVO OFFERINGS WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, BE TIMELY, SECURE, ACCURATE, OR BE UNINTERRUPTED, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, THE AIVO PARTIES DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER STATUTORY, EXPRESS, OR IMPLIED, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, QUALITY, ACCURACY, PERFORMANCE, AVAILABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.",
            "16.2. AI-Enabled Features. YOU ACKNOWLEDGE AND AGREE THAT OUTPUT FROM BRAIN-CLONE OR OTHER AI-ENABLED FEATURES MAY INCLUDE ERRORS (INCLUDING WITHOUT LIMITATION MATH ERRORS), MAY REFLECT BIASED, INCOMPLETE, OR INCORRECT INFORMATION, MAY PROVIDE OBJECTIONABLE OR OFFENSIVE RESPONSES, MAY NOT ACCOUNT FOR EVENTS OR CHANGES TO UNDERLYING FACTS OCCURRING AFTER THE AI MODEL WAS TRAINED, AND HAVE OTHER LIMITATIONS. YOU SHOULD NOT RELY ON THE FACTUAL ASSERTIONS IN OUTPUT WITHOUT INDEPENDENTLY FACT CHECKING THEIR ACCURACY. AIVO IS AN EDUCATIONAL TOOL AND IS NOT A SUBSTITUTE FOR PROFESSIONAL MEDICAL, THERAPEUTIC, SPECIAL EDUCATION, OR LEGAL ADVICE.",
            "16.3. Limitations by Applicable Law. SOME STATES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM STATE TO STATE AND JURISDICTION TO JURISDICTION.",
          ],
        },
        {
          title: "17. Limitation of Liability and Damages",
          content: [
            "17.1. Limitation of Liability. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES WILL THE AIVO PARTIES BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, COVER, BUSINESS INTERRUPTION, PUNITIVE, RELIANCE, OR EXEMPLARY DAMAGES (INCLUDING WITHOUT LIMITATION LOST BUSINESS, LOST REVENUES OR PROFITS, LOSS OF DATA, OR ANY OTHER PECUNIARY OR NON-PECUNIARY LOSS OR DAMAGE OF ANY NATURE) ARISING OUT OF OR RELATING (i) TO THE TERMS, (ii) YOUR USE OF (OR INABILITY TO USE) THE WEBSITE OR THE AIVO OFFERINGS, OR (iii) ANY OTHER INTERACTIONS WITH AIVO OR ANY THIRD PARTY THROUGH OR IN CONNECTION WITH THE AIVO OFFERINGS, EVEN IF AIVO OR AN AIVO PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
            "17.2. Limitation of Damages. IN NO EVENT WILL THE AIVO PARTIES' TOTAL AGGREGATE LIABILITY TO YOU, FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THE TERMS, YOUR USE OF ANY AIVO OFFERING, OR YOUR INTERACTION WITH OTHER USERS (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), WARRANTY, OR OTHERWISE), EXCEED THE GREATER OF THE ACTUAL AMOUNT PAID BY YOU TO AIVO, IF ANY, DURING THE TWELVE MONTHS IMMEDIATELY PRECEDING THE DATE OF THE CLAIM OR ONE HUNDRED DOLLARS ($100). FOR CLARITY, IF YOU ARE ACCESSING THE SERVICES FOR SCHOOL USE OR ON BEHALF OF AN INSTITUTION, THIS AGGREGATE CAP ON LIABILITY WILL BE MEASURED BY THE AMOUNT PAID BY YOUR SCHOOL OR INSTITUTION TO AIVO IN THE PRECEDING TWELVE MONTHS (OR ONE HUNDRED DOLLARS ($100), IF NO SUCH PAYMENT), AND APPLIES TO ALL DAMAGES SUFFERED BY YOU, YOUR SCHOOL, OR INSTITUTION, AND ALL OTHER USERS FROM YOUR SCHOOL OR INSTITUTION, COLLECTIVELY.",
            "17.3. Basis of the Bargain. YOU ACKNOWLEDGE AND AGREE THAT AIVO HAS OFFERED THE SERVICES AND ENTERED INTO THE TERMS IN RELIANCE UPON THE DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH HEREIN, THAT THESE DISCLAIMERS AND LIMITATIONS REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND AIVO, AND THAT THEY FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN YOU AND AIVO.",
            "17.4. User Interactions and Release. AIVO is not responsible for the actions, content, information, or data of other third parties, including other Users. You are solely responsible for your interactions with other Users of the Services. If you have a dispute with one or more Users, you release us (and the AIVO Parties) from all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes.",
          ],
        },
        {
          title: "18. Miscellaneous (Including Dispute Resolution and Arbitration)",
          content: [
            "18.1. Notice. AIVO may provide you with notices, including those regarding changes to the Terms, by email, regular mail, postings on the website or Services, or other reasonable means. Notice will be deemed given twenty-four hours after email is sent. Any notices directed to AIVO shall be sent by first-class U.S. Mail to Aivo AI Learning Technologies Inc., with a copy by email to legal@aivolearning.com.",
            "18.2. Waiver. The failure of AIVO to exercise or enforce any right or provision of the Terms will not constitute a waiver of such right or provision. Any waiver of any provision of the Terms will be effective only if in writing and signed by AIVO.",
            "18.3. Governing Law. The Terms will be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any principles of conflicts of law that would cause the application of the laws of any other jurisdiction.",
            "18.4. Dispute Resolution and Arbitration. PLEASE READ THIS SECTION CAREFULLY BECAUSE IT AFFECTS YOUR RIGHTS. EXCEPT AS REQUIRED BY APPLICABLE LAW, BY AGREEING TO BINDING ARBITRATION, YOU WAIVE YOUR RIGHT TO LITIGATE DISPUTES THROUGH A COURT AND TO HAVE A JUDGE OR JURY DECIDE YOUR CASE. YOU ALSO AGREE TO WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION, CLASS ARBITRATION, OR OTHER REPRESENTATIVE ACTION. TO THE FULLEST EXTENT PERMITTED BY LAW, IF A DISPUTE IS NOT FILED WITHIN ONE YEAR, IT IS PERMANENTLY BARRED.",
            "18.4.1. Notice of Dispute. In the event of a Dispute, you or AIVO must give the other a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the Dispute, and a proposed solution (a \"Notice of Dispute\"). You and AIVO will attempt in good faith to resolve any Dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent.",
            "18.4.2. Binding Arbitration. Any Dispute which has not been resolved by negotiation within sixty (60) days shall be finally resolved by binding arbitration administered by the American Arbitration Association (\"AAA\") under its Consumer Arbitration Rules. The U.S. Federal Arbitration Act governs the interpretation and enforcement of this Section 18.4. The place of arbitration shall be Wilmington, Delaware. Any court with jurisdiction over the parties may enforce the arbitrator's award.",
            "18.4.3. Class Action Waiver. Any proceedings to resolve or litigate any Dispute in any forum will be conducted solely on an individual basis. Neither you nor AIVO will seek to have any Dispute heard as a class action or in any other proceeding in which either party acts or proposes to act in a representative capacity.",
            "18.4.4. Arbitrator's Jurisdiction. The arbitrator will have the power to rule on all issues except that a court has authority (i) to decide arbitrability issues, (ii) to enforce the prohibition on class or representative actions, and (iii) to award injunctive or other equitable relief to protect or enforce either party's intellectual property rights.",
            "18.4.5. Filing Period. To the extent permitted by law, any Dispute under these Terms must be filed within one (1) year. The one-year period begins when the events giving rise to the Dispute first occur, except that the period is tolled during the 60-day Notice of Dispute process.",
            "18.4.6. Venue. In the event that any Dispute cannot be resolved by binding arbitration, you agree that such Dispute will be filed only in the state or federal courts in and for New Castle County, Delaware, and each of you and AIVO consents and submits to the personal and exclusive jurisdiction of such courts.",
            "18.5. Severability. If any provision of the Terms or any Guidelines is held to be unlawful, void, or for any reason unenforceable, then that provision will be limited or eliminated from the Terms to the minimum extent necessary and will not affect the validity and enforceability of any remaining provisions.",
            "18.6. Assignment. The Terms and related Guidelines, and any rights and licenses granted hereunder, may not be transferred or assigned by you without AIVO's prior written consent, but may be assigned by AIVO without consent or any restriction.",
            "18.7. Survival. Upon termination of the Terms, any provision which, by its nature or express terms should survive, will survive such termination, including, but not limited to, Sections 5.1, 6, 7, 8, 9, 12.1, 13.2, 13.5, 14, 15, 16, 17, and 18.",
            "18.8. Entire Agreement. The Terms, the Privacy Policy, and Guidelines constitute the entire agreement between you and AIVO relating to the subject matter herein and will not be modified except in writing, signed by both parties, pursuant to supplemental terms as set forth in Section 5.2, or by a change to the Terms or Privacy Policy made by AIVO as set forth in Section 12.",
            "18.9. Disclosures. The Services are hosted in the United States, and the Services provided hereunder are offered by Aivo AI Learning Technologies Inc. For questions about these Terms, please contact us at legal@aivolearning.com.",
          ],
        },
      ]}
    />
  );
}
