/**
 * Fallback chapter activities used by `useDiscoveryEngine` when the
 * learner has no auth token (anonymous demo) or the AI generation
 * endpoint is unreachable. Extracted out of `useDiscoveryEngine.ts`
 * (which previously embedded this constant inline at ~493 lines) so
 * the engine module stays focused on session/state logic.
 *
 * NOTE: This is the legacy authoring shape (`tutorLine`, `interaction`,
 * `sceneEmoji`, `brainMeasures`). The replacement migration to the
 * `@aivo/content-pack` schema (`@aivo/content-pack` `Activity`, with
 * `prompt`, `assetRefs`, etc.) is tracked separately and will replace
 * this module entirely.
 */
import type { ChapterActivities } from "./types";

const FALLBACK_ACTIVITIES: Record<string, ChapterActivities> = {
  sage_story_garden: {
    easy: [
      { id: "ela_e1", title: "The Word Garden", narration: "Welcome to my garden! Look at the cat — can you find the word that matches what the cat is doing?", tutorLine: "Look at the cat. Which word tells us what the cat is doing?", interaction: "tap_image", choices: [{ id: "a", label: "Sleeping", emoji: "😴", isCorrect: false }, { id: "b", label: "Running", emoji: "🏃", isCorrect: true }, { id: "c", label: "Eating", emoji: "🍽️", isCorrect: false }], sceneEmoji: "🐈💨", difficulty: "easy", brainMeasures: ["vocabulary"] },
      { id: "ela_e2", title: "Story Stream", narration: "Look! A story is floating down the stream. Let me read it to you!", tutorLine: "The bird flew to the tree. Where did the bird go?", interaction: "tap_image", choices: [{ id: "a", label: "Tree", emoji: "🌲", isCorrect: true }, { id: "b", label: "House", emoji: "🏠", isCorrect: false }, { id: "c", label: "Lake", emoji: "🏊", isCorrect: false }], sceneEmoji: "🌊", difficulty: "easy", brainMeasures: ["comprehension"] },
      { id: "ela_e3", title: "Rhyme Time", narration: "The flowers in my garden love to rhyme! Can you find the rhyming word?", tutorLine: "Which word rhymes with 'cat'?", interaction: "tap_word", choices: [{ id: "a", label: "Hat", emoji: "🎩", isCorrect: true }, { id: "b", label: "Dog", emoji: "🐕", isCorrect: false }, { id: "c", label: "Cup", emoji: "☕", isCorrect: false }], sceneEmoji: "🌸", difficulty: "easy", brainMeasures: ["phonics"] },
    ],
    medium: [
      { id: "ela_m1", title: "Word Garden", narration: "These special trees grow bigger words! Let's explore them together.", tutorLine: "What does the word 'enormous' mean?", interaction: "tap_image", choices: [{ id: "a", label: "Very small", emoji: "🐜", isCorrect: false }, { id: "b", label: "Very big", emoji: "🦕", isCorrect: true }, { id: "c", label: "Very fast", emoji: "⚡", isCorrect: false }, { id: "d", label: "Very quiet", emoji: "🤫", isCorrect: false }], sceneEmoji: "🌳", difficulty: "medium", brainMeasures: ["vocabulary"] },
      { id: "ela_m2", title: "Story Detective", narration: "A mysterious story appeared in the garden! Can you figure out what happened?", tutorLine: "Sam was sad because his kite got stuck. What happened to the kite?", interaction: "tap_image", choices: [{ id: "a", label: "It flew away", emoji: "🦅", isCorrect: false }, { id: "b", label: "It got stuck", emoji: "🌳", isCorrect: true }, { id: "c", label: "It broke", emoji: "💔", isCorrect: false }, { id: "d", label: "It landed", emoji: "🛬", isCorrect: false }], sceneEmoji: "🔍", difficulty: "medium", brainMeasures: ["comprehension"] },
      { id: "ela_m3", title: "Sentence Garden", narration: "The sentence vines are tangled! Help me sort them out.", tutorLine: "Which sentence is correct?", interaction: "tap_word", choices: [{ id: "a", label: "The dog runs fast.", emoji: "🐕", isCorrect: true }, { id: "b", label: "Dog the runs fast.", emoji: "🔄", isCorrect: false }, { id: "c", label: "Runs the dog fast.", emoji: "❌", isCorrect: false }, { id: "d", label: "Fast dog the runs.", emoji: "🤔", isCorrect: false }], sceneEmoji: "🌿", difficulty: "medium", brainMeasures: ["grammar", "syntax"] },
      { id: "ela_m4", title: "Main Idea Meadow", narration: "Every story has a main idea hiding in it. Let's find it!", tutorLine: "The story is about a dog who learns to swim. What is the main idea?", interaction: "tap_image", choices: [{ id: "a", label: "A dog learns something new", emoji: "🐶", isCorrect: true }, { id: "b", label: "Water is cold", emoji: "🥶", isCorrect: false }, { id: "c", label: "Dogs like food", emoji: "🦴", isCorrect: false }, { id: "d", label: "Swimming is easy", emoji: "🏊", isCorrect: false }], sceneEmoji: "🌻", difficulty: "medium", brainMeasures: ["main idea"] },
    ],
    hard: [
      { id: "ela_h1", title: "Advanced Word Garden", narration: "The rarest words in my garden are blooming! These are special.", tutorLine: "Choose the word that means 'to make something better':", interaction: "tap_word", choices: [{ id: "a", label: "Improve", emoji: "⬆️", isCorrect: true }, { id: "b", label: "Destroy", emoji: "💥", isCorrect: false }, { id: "c", label: "Ignore", emoji: "🙈", isCorrect: false }, { id: "d", label: "Delay", emoji: "⏰", isCorrect: false }], sceneEmoji: "🌺", difficulty: "hard", brainMeasures: ["vocabulary", "inference"] },
      { id: "ela_h2", title: "Author's Purpose", narration: "Every author writes for a reason. Can you figure out why?", tutorLine: "A book teaches you how to bake cookies. The author's purpose is to:", interaction: "tap_word", choices: [{ id: "a", label: "Inform", emoji: "📘", isCorrect: true }, { id: "b", label: "Entertain", emoji: "🎭", isCorrect: false }, { id: "c", label: "Persuade", emoji: "📢", isCorrect: false }, { id: "d", label: "Confuse", emoji: "😵", isCorrect: false }], sceneEmoji: "📖", difficulty: "hard", brainMeasures: ["author's purpose"] },
      { id: "ela_h3", title: "Inference Ivy", narration: "Sometimes what's NOT said is just as important!", tutorLine: "The ground was wet and people carried umbrellas. What probably happened?", interaction: "tap_image", choices: [{ id: "a", label: "It rained", emoji: "🌧️", isCorrect: true }, { id: "b", label: "It snowed", emoji: "❄️", isCorrect: false }, { id: "c", label: "It was sunny", emoji: "☀️", isCorrect: false }, { id: "d", label: "It was windy", emoji: "🌬️", isCorrect: false }], sceneEmoji: "🔎", difficulty: "hard", brainMeasures: ["inference"] },
    ],
  },
  nova_number_galaxy: {
    easy: [
      { id: "math_e1", title: "Star Counting", narration: "Look at all these beautiful stars! Let's count them together!", tutorLine: "How many stars do you see? ⭐⭐⭐⭐⭐", interaction: "tap_image", choices: [{ id: "a", label: "3", emoji: "3️⃣", isCorrect: false }, { id: "b", label: "5", emoji: "5️⃣", isCorrect: true }, { id: "c", label: "7", emoji: "7️⃣", isCorrect: false }], sceneEmoji: "🌌", difficulty: "easy", brainMeasures: ["number sense"] },
      { id: "math_e2", title: "Planet Puzzles", narration: "A planet with 3 moons met a planet with 2 moons!", tutorLine: "How many moons are there altogether?", interaction: "tap_image", choices: [{ id: "a", label: "4", emoji: "4️⃣", isCorrect: false }, { id: "b", label: "5", emoji: "5️⃣", isCorrect: true }, { id: "c", label: "6", emoji: "6️⃣", isCorrect: false }], sceneEmoji: "🪐", difficulty: "easy", brainMeasures: ["addition"] },
      { id: "math_e3", title: "Asteroid Shapes", narration: "The asteroids come in different shapes! Can you find the right one?", tutorLine: "Which shape has 3 sides?", interaction: "tap_image", choices: [{ id: "a", label: "Triangle", emoji: "🔺", isCorrect: true }, { id: "b", label: "Square", emoji: "⬛", isCorrect: false }, { id: "c", label: "Circle", emoji: "⚪", isCorrect: false }], sceneEmoji: "☄️", difficulty: "easy", brainMeasures: ["geometry"] },
      { id: "math_e4", title: "Number Neighbors", narration: "Numbers have neighbors! Let's find who lives next door.", tutorLine: "What number comes after 7?", interaction: "tap_image", choices: [{ id: "a", label: "8", emoji: "8️⃣", isCorrect: true }, { id: "b", label: "6", emoji: "6️⃣", isCorrect: false }, { id: "c", label: "9", emoji: "9️⃣", isCorrect: false }], sceneEmoji: "🏘️", difficulty: "easy", brainMeasures: ["number sequence"] },
      { id: "math_e5", title: "Space Comparison", narration: "Which planet is bigger? Let's compare!", tutorLine: "Which number is bigger: 3 or 8?", interaction: "tap_image", choices: [{ id: "a", label: "8", emoji: "8️⃣", isCorrect: true }, { id: "b", label: "3", emoji: "3️⃣", isCorrect: false }, { id: "c", label: "Same", emoji: "🟰", isCorrect: false }], sceneEmoji: "📏", difficulty: "easy", brainMeasures: ["comparison"] },
    ],
    medium: [
      { id: "math_m1", title: "Star Clusters", narration: "These stars are arranged in a special pattern. Can you figure it out?", tutorLine: "There are 3 rows of 4 stars. How many stars total?", interaction: "tap_image", choices: [{ id: "a", label: "7", emoji: "7️⃣", isCorrect: false }, { id: "b", label: "10", emoji: "🔟", isCorrect: false }, { id: "c", label: "12", emoji: "1️⃣2️⃣", isCorrect: true }, { id: "d", label: "15", emoji: "1️⃣5️⃣", isCorrect: false }], sceneEmoji: "✨", difficulty: "medium", brainMeasures: ["multiplication"] },
      { id: "math_m2", title: "Fraction Nebula", narration: "This pizza planet has been cut into equal slices!", tutorLine: "If a pizza is cut into 4 equal slices and you eat 1, what fraction is left?", interaction: "tap_image", choices: [{ id: "a", label: "3/4", emoji: "🍕", isCorrect: true }, { id: "b", label: "1/2", emoji: "➗", isCorrect: false }, { id: "c", label: "2/4", emoji: "🔢", isCorrect: false }, { id: "d", label: "1/4", emoji: "🍰", isCorrect: false }], sceneEmoji: "🌀", difficulty: "medium", brainMeasures: ["fractions"] },
      { id: "math_m3", title: "Word Problem Warp", narration: "A cosmic word problem is heading our way!", tutorLine: "You have 15 space gems and give away 7. How many are left?", interaction: "tap_image", choices: [{ id: "a", label: "8", emoji: "8️⃣", isCorrect: true }, { id: "b", label: "7", emoji: "7️⃣", isCorrect: false }, { id: "c", label: "9", emoji: "9️⃣", isCorrect: false }, { id: "d", label: "22", emoji: "🔢", isCorrect: false }], sceneEmoji: "💎", difficulty: "medium", brainMeasures: ["subtraction", "word problems"] },
    ],
    hard: [
      { id: "math_h1", title: "Galaxy Equations", narration: "The deepest part of the galaxy has the trickiest challenges!", tutorLine: "If 24 stars are shared equally among 6 planets, how many stars per planet?", interaction: "tap_image", choices: [{ id: "a", label: "3", emoji: "3️⃣", isCorrect: false }, { id: "b", label: "4", emoji: "4️⃣", isCorrect: true }, { id: "c", label: "5", emoji: "5️⃣", isCorrect: false }, { id: "d", label: "6", emoji: "6️⃣", isCorrect: false }], sceneEmoji: "🌠", difficulty: "hard", brainMeasures: ["division"] },
      { id: "math_h2", title: "Pattern Predictor", narration: "The universe follows patterns. Can you predict the next?", tutorLine: "2, 4, 8, 16, ___?", interaction: "tap_image", choices: [{ id: "a", label: "32", emoji: "🔢", isCorrect: true }, { id: "b", label: "24", emoji: "2️⃣4️⃣", isCorrect: false }, { id: "c", label: "18", emoji: "1️⃣8️⃣", isCorrect: false }, { id: "d", label: "20", emoji: "2️⃣0️⃣", isCorrect: false }], sceneEmoji: "🔮", difficulty: "hard", brainMeasures: ["patterns", "doubling"] },
      { id: "math_h3", title: "Multi-Step Mission", narration: "This mission needs more than one step to solve!", tutorLine: "A spaceship has 30 seats. 12 are taken and 5 more people arrive. How many seats are empty?", interaction: "tap_image", choices: [{ id: "a", label: "13", emoji: "1️⃣3️⃣", isCorrect: true }, { id: "b", label: "18", emoji: "1️⃣8️⃣", isCorrect: false }, { id: "c", label: "23", emoji: "2️⃣3️⃣", isCorrect: false }, { id: "d", label: "15", emoji: "1️⃣5️⃣", isCorrect: false }], sceneEmoji: "🚀", difficulty: "hard", brainMeasures: ["multi-step", "operations"] },
    ],
  },
  spark_discovery_lab: {
    easy: [
      { id: "sci_e1", title: "Sorting Station", narration: "My lab is a mess! Can you help me figure out which ones are living things?", tutorLine: "Which one is alive?", interaction: "tap_image", choices: [{ id: "a", label: "Rock", emoji: "🪨", isCorrect: false }, { id: "b", label: "Flower", emoji: "🌻", isCorrect: true }, { id: "c", label: "Cup", emoji: "☕", isCorrect: false }], sceneEmoji: "🧪", difficulty: "easy", brainMeasures: ["classification"] },
      { id: "sci_e2", title: "Weather Window", narration: "Look out the window! What do you see happening outside?", tutorLine: "What kind of weather do you see? ☁️💧", interaction: "tap_image", choices: [{ id: "a", label: "Sunny", emoji: "☀️", isCorrect: false }, { id: "b", label: "Rainy", emoji: "🌧️", isCorrect: true }, { id: "c", label: "Snowy", emoji: "❄️", isCorrect: false }], sceneEmoji: "🌤️", difficulty: "easy", brainMeasures: ["observation"] },
      { id: "sci_e3", title: "Animal Homes", narration: "Every animal has a home! Let's match them.", tutorLine: "Where does a fish live?", interaction: "tap_image", choices: [{ id: "a", label: "Water", emoji: "🌊", isCorrect: true }, { id: "b", label: "Tree", emoji: "🌲", isCorrect: false }, { id: "c", label: "Cave", emoji: "🕳️", isCorrect: false }], sceneEmoji: "🏠", difficulty: "easy", brainMeasures: ["habitats"] },
      { id: "sci_e4", title: "Senses Lab", narration: "We use our senses every day! Which sense helps here?", tutorLine: "Which sense do you use to hear music?", interaction: "tap_image", choices: [{ id: "a", label: "Ears", emoji: "👂", isCorrect: true }, { id: "b", label: "Eyes", emoji: "👀", isCorrect: false }, { id: "c", label: "Nose", emoji: "👃", isCorrect: false }], sceneEmoji: "🔊", difficulty: "easy", brainMeasures: ["senses"] },
      { id: "sci_e5", title: "Day and Night", narration: "The sky changes throughout the day!", tutorLine: "When do you see the moon?", interaction: "tap_image", choices: [{ id: "a", label: "Night", emoji: "🌙", isCorrect: true }, { id: "b", label: "Morning", emoji: "🌅", isCorrect: false }, { id: "c", label: "Noon", emoji: "☀️", isCorrect: false }], sceneEmoji: "🌓", difficulty: "easy", brainMeasures: ["earth science"] },
    ],
    medium: [
      { id: "sci_m1", title: "The Experiment", narration: "Let's do an experiment! If I push this ball off the table...", tutorLine: "What will happen to the ball?", interaction: "tap_image", choices: [{ id: "a", label: "It flies up", emoji: "⬆️", isCorrect: false }, { id: "b", label: "It falls down", emoji: "⬇️", isCorrect: true }, { id: "c", label: "It disappears", emoji: "💨", isCorrect: false }, { id: "d", label: "Nothing", emoji: "🤷", isCorrect: false }], sceneEmoji: "⚗️", difficulty: "medium", brainMeasures: ["cause and effect"] },
      { id: "sci_m2", title: "Plant Life", narration: "Plants are amazing! They need special things to grow.", tutorLine: "What do plants need to grow?", interaction: "tap_image", choices: [{ id: "a", label: "Sunlight and water", emoji: "🌱", isCorrect: true }, { id: "b", label: "Toys", emoji: "🧸", isCorrect: false }, { id: "c", label: "Music", emoji: "🎵", isCorrect: false }, { id: "d", label: "Candy", emoji: "🍬", isCorrect: false }], sceneEmoji: "🌿", difficulty: "medium", brainMeasures: ["life science"] },
      { id: "sci_m3", title: "States of Matter", narration: "Water can change its form! It's science magic.", tutorLine: "When water freezes, it becomes:", interaction: "tap_image", choices: [{ id: "a", label: "Ice", emoji: "🧊", isCorrect: true }, { id: "b", label: "Steam", emoji: "♨️", isCorrect: false }, { id: "c", label: "Air", emoji: "💨", isCorrect: false }, { id: "d", label: "Juice", emoji: "🧃", isCorrect: false }], sceneEmoji: "🔬", difficulty: "medium", brainMeasures: ["states of matter"] },
    ],
    hard: [
      { id: "sci_h1", title: "Deep Discovery", narration: "Time for advanced science! The water cycle is fascinating.", tutorLine: "When water heats up and turns into vapor, what is that called?", interaction: "tap_word", choices: [{ id: "a", label: "Evaporation", emoji: "💨", isCorrect: true }, { id: "b", label: "Condensation", emoji: "💧", isCorrect: false }, { id: "c", label: "Precipitation", emoji: "🌧️", isCorrect: false }, { id: "d", label: "Collection", emoji: "🏊", isCorrect: false }], sceneEmoji: "🔬", difficulty: "hard", brainMeasures: ["scientific vocabulary"] },
      { id: "sci_h2", title: "Food Chain", narration: "In nature, living things depend on each other!", tutorLine: "In a food chain: grass → rabbit → fox. What does the fox eat?", interaction: "tap_image", choices: [{ id: "a", label: "Rabbit", emoji: "🐇", isCorrect: true }, { id: "b", label: "Grass", emoji: "🌾", isCorrect: false }, { id: "c", label: "Fish", emoji: "🐟", isCorrect: false }, { id: "d", label: "Berries", emoji: "🫐", isCorrect: false }], sceneEmoji: "🔗", difficulty: "hard", brainMeasures: ["food chains", "ecosystems"] },
      { id: "sci_h3", title: "Energy Explorer", narration: "Energy is everywhere! Let's figure out what kind.", tutorLine: "A light bulb converts electricity into:", interaction: "tap_image", choices: [{ id: "a", label: "Light and heat", emoji: "💡", isCorrect: true }, { id: "b", label: "Sound", emoji: "🔊", isCorrect: false }, { id: "c", label: "Motion", emoji: "🏃", isCorrect: false }, { id: "d", label: "Water", emoji: "💧", isCorrect: false }], sceneEmoji: "⚡", difficulty: "hard", brainMeasures: ["energy", "transformations"] },
    ],
  },
  harmony_feelings_treehouse: {
    easy: [
      { id: "sel_e1", title: "Emotion Mirror", narration: "Welcome to my cozy treehouse! Let's talk about feelings.", tutorLine: "This person dropped their ice cream. How do they feel?", interaction: "emotion_pick", choices: [{ id: "a", label: "Happy", emoji: "😊", isCorrect: false }, { id: "b", label: "Sad", emoji: "😢", isCorrect: true }, { id: "c", label: "Angry", emoji: "😠", isCorrect: false }], sceneEmoji: "🪞", difficulty: "easy", brainMeasures: ["emotion recognition"] },
      { id: "sel_e2", title: "Story Scenarios", narration: "Let me tell you about Alex and Jordan. They both want the same toy.", tutorLine: "What is a kind thing they could do?", interaction: "tap_image", choices: [{ id: "a", label: "Take turns", emoji: "🔄", isCorrect: true }, { id: "b", label: "Grab it", emoji: "✊", isCorrect: false }, { id: "c", label: "Walk away angry", emoji: "😤", isCorrect: false }], sceneEmoji: "🧸", difficulty: "easy", brainMeasures: ["social reasoning"] },
      { id: "sel_e3", title: "Feelings Faces", narration: "Our faces show how we feel! Let's learn the clues.", tutorLine: "When someone smiles really big, they probably feel:", interaction: "emotion_pick", choices: [{ id: "a", label: "Happy", emoji: "😊", isCorrect: true }, { id: "b", label: "Scared", emoji: "😨", isCorrect: false }, { id: "c", label: "Tired", emoji: "😴", isCorrect: false }], sceneEmoji: "😃", difficulty: "easy", brainMeasures: ["emotion recognition"] },
      { id: "sel_e4", title: "Being a Friend", narration: "Good friends do nice things for each other!", tutorLine: "Your friend fell down. What would a good friend do?", interaction: "tap_image", choices: [{ id: "a", label: "Help them up", emoji: "🤝", isCorrect: true }, { id: "b", label: "Laugh", emoji: "😂", isCorrect: false }, { id: "c", label: "Run away", emoji: "🏃", isCorrect: false }], sceneEmoji: "💕", difficulty: "easy", brainMeasures: ["prosocial behavior"] },
      { id: "sel_e5", title: "Calm Corner", narration: "Everyone gets upset sometimes. That's okay!", tutorLine: "When you feel worried, what can help you feel better?", interaction: "tap_image", choices: [{ id: "a", label: "Hug a stuffed animal", emoji: "🧸", isCorrect: true }, { id: "b", label: "Throw things", emoji: "🤾", isCorrect: false }, { id: "c", label: "Scream loudly", emoji: "😱", isCorrect: false }], sceneEmoji: "🌈", difficulty: "easy", brainMeasures: ["coping strategies"] },
    ],
    medium: [
      { id: "sel_m1", title: "Feelings Check", narration: "Sometimes big feelings can be hard to handle. That's totally normal!", tutorLine: "When you feel angry, what is a helpful thing to do?", interaction: "tap_image", choices: [{ id: "a", label: "Take deep breaths", emoji: "🌬️", isCorrect: true }, { id: "b", label: "Yell at someone", emoji: "😡", isCorrect: false }, { id: "c", label: "Break something", emoji: "💥", isCorrect: false }, { id: "d", label: "Hide forever", emoji: "🫥", isCorrect: false }], sceneEmoji: "💛", difficulty: "medium", brainMeasures: ["self-regulation"] },
      { id: "sel_m2", title: "Perspective Window", narration: "Let's look through someone else's eyes!", tutorLine: "Your friend is crying because they lost their pet. You should:", interaction: "tap_image", choices: [{ id: "a", label: "Say you're sorry and listen", emoji: "💜", isCorrect: true }, { id: "b", label: "Tell them to stop crying", emoji: "🤫", isCorrect: false }, { id: "c", label: "Talk about your pet instead", emoji: "🐕", isCorrect: false }, { id: "d", label: "Walk away", emoji: "🚶", isCorrect: false }], sceneEmoji: "🪟", difficulty: "medium", brainMeasures: ["empathy", "perspective-taking"] },
      { id: "sel_m3", title: "Conflict Corner", narration: "Sometimes people disagree. That's normal! What matters is how we handle it.", tutorLine: "Two friends want to play different games at recess. The best solution is:", interaction: "tap_image", choices: [{ id: "a", label: "Compromise or take turns", emoji: "🤝", isCorrect: true }, { id: "b", label: "One person always decides", emoji: "👆", isCorrect: false }, { id: "c", label: "Neither plays", emoji: "❌", isCorrect: false }, { id: "d", label: "Ask a teacher to pick", emoji: "👩‍🏫", isCorrect: false }], sceneEmoji: "⚖️", difficulty: "medium", brainMeasures: ["conflict resolution"] },
    ],
    hard: [
      { id: "sel_h1", title: "Empathy Explorer", narration: "Understanding others is a superpower!", tutorLine: "Your friend seems quiet today and isn't playing. What might help?", interaction: "tap_image", choices: [{ id: "a", label: "Ask if they're okay", emoji: "💬", isCorrect: true }, { id: "b", label: "Ignore them", emoji: "🙈", isCorrect: false }, { id: "c", label: "Tell them to be happy", emoji: "😁", isCorrect: false }, { id: "d", label: "Laugh at them", emoji: "🤣", isCorrect: false }], sceneEmoji: "🤝", difficulty: "hard", brainMeasures: ["empathy", "perspective-taking"] },
      { id: "sel_h2", title: "Growth Mindset", narration: "The way we think about challenges matters a lot!", tutorLine: "You got a bad grade on a test. Which thought is most helpful?", interaction: "tap_image", choices: [{ id: "a", label: "I can learn from mistakes", emoji: "🌱", isCorrect: true }, { id: "b", label: "I'm just not smart", emoji: "😞", isCorrect: false }, { id: "c", label: "Tests are unfair", emoji: "😤", isCorrect: false }, { id: "d", label: "I'll never try again", emoji: "🚫", isCorrect: false }], sceneEmoji: "🧠", difficulty: "hard", brainMeasures: ["growth mindset", "resilience"] },
      { id: "sel_h3", title: "Complex Emotions", narration: "Sometimes we feel more than one thing at the same time!", tutorLine: "Moving to a new school can make you feel:", interaction: "tap_image", choices: [{ id: "a", label: "Excited AND nervous", emoji: "🤔", isCorrect: true }, { id: "b", label: "Only happy", emoji: "😊", isCorrect: false }, { id: "c", label: "Only sad", emoji: "😢", isCorrect: false }, { id: "d", label: "Nothing", emoji: "😐", isCorrect: false }], sceneEmoji: "🎭", difficulty: "hard", brainMeasures: ["emotional complexity"] },
    ],
  },
  echo_sound_studio: {
    easy: [
      { id: "sp_e1", title: "Sound Safari", narration: "Welcome to my studio! Let's listen to some sounds.", tutorLine: "Which animal makes a 'moo' sound?", interaction: "tap_image", choices: [{ id: "a", label: "Dog", emoji: "🐕", isCorrect: false }, { id: "b", label: "Cow", emoji: "🐄", isCorrect: true }, { id: "c", label: "Cat", emoji: "🐱", isCorrect: false }], sceneEmoji: "🎤", difficulty: "easy", brainMeasures: ["sound discrimination"] },
      { id: "sp_e2", title: "Word Builder", narration: "Let's play with words! Some words start with the same sound.", tutorLine: "Which word starts with the same sound as 'ball'?", interaction: "tap_image", choices: [{ id: "a", label: "Bear", emoji: "🐻", isCorrect: true }, { id: "b", label: "Cat", emoji: "🐱", isCorrect: false }, { id: "c", label: "Fish", emoji: "🐟", isCorrect: false }], sceneEmoji: "🔤", difficulty: "easy", brainMeasures: ["phonemic awareness"] },
      { id: "sp_e3", title: "Rhyme Time", narration: "My studio echoes with rhymes! Can you find the match?", tutorLine: "Which word rhymes with 'moon'?", interaction: "tap_image", choices: [{ id: "a", label: "Spoon", emoji: "🥄", isCorrect: true }, { id: "b", label: "Star", emoji: "⭐", isCorrect: false }, { id: "c", label: "Bird", emoji: "🐦", isCorrect: false }], sceneEmoji: "🌙", difficulty: "easy", brainMeasures: ["rhyming"] },
      { id: "sp_e4", title: "Sentence Builder", narration: "Let's put words together to make a sentence!", tutorLine: "Which word completes the sentence: 'The dog ___ fast.'?", interaction: "tap_word", choices: [{ id: "a", label: "runs", emoji: "🏃", isCorrect: true }, { id: "b", label: "blue", emoji: "🔵", isCorrect: false }, { id: "c", label: "big", emoji: "🐘", isCorrect: false }], sceneEmoji: "📝", difficulty: "easy", brainMeasures: ["grammar"] },
      { id: "sp_e5", title: "Listening Corner", narration: "Let's practice listening carefully!", tutorLine: "If someone says 'Can I have some water please?', what do they want?", interaction: "tap_image", choices: [{ id: "a", label: "Water", emoji: "💧", isCorrect: true }, { id: "b", label: "Food", emoji: "🍎", isCorrect: false }, { id: "c", label: "A toy", emoji: "🧸", isCorrect: false }], sceneEmoji: "👂", difficulty: "easy", brainMeasures: ["comprehension"] },
    ],
    medium: [
      { id: "sp_m1", title: "Syllable Beats", narration: "Words have beats just like music! Let's clap them out.", tutorLine: "How many syllables in 'butterfly'? 🦋", interaction: "tap_image", choices: [{ id: "a", label: "2", emoji: "2️⃣", isCorrect: false }, { id: "b", label: "3", emoji: "3️⃣", isCorrect: true }, { id: "c", label: "4", emoji: "4️⃣", isCorrect: false }, { id: "d", label: "1", emoji: "1️⃣", isCorrect: false }], sceneEmoji: "🎵", difficulty: "medium", brainMeasures: ["syllable awareness"] },
      { id: "sp_m2", title: "Word Pairs", narration: "Some words mean the same thing! Let's find matches.", tutorLine: "Which word means the same as 'happy'?", interaction: "tap_word", choices: [{ id: "a", label: "Glad", emoji: "😊", isCorrect: true }, { id: "b", label: "Angry", emoji: "😠", isCorrect: false }, { id: "c", label: "Tired", emoji: "😴", isCorrect: false }, { id: "d", label: "Hungry", emoji: "🍽️", isCorrect: false }], sceneEmoji: "🔗", difficulty: "medium", brainMeasures: ["vocabulary"] },
      { id: "sp_m3", title: "Story Telling", narration: "Let's put this story in the right order!", tutorLine: "What comes first: brush teeth, wake up, or eat breakfast?", interaction: "tap_image", choices: [{ id: "a", label: "Wake up", emoji: "⏰", isCorrect: true }, { id: "b", label: "Brush teeth", emoji: "🪥", isCorrect: false }, { id: "c", label: "Eat breakfast", emoji: "🥣", isCorrect: false }, { id: "d", label: "Go to school", emoji: "🏫", isCorrect: false }], sceneEmoji: "📖", difficulty: "medium", brainMeasures: ["sequencing", "pragmatic language"] },
      { id: "sp_m4", title: "Opposite Day", narration: "Everything is backwards today! Let's find opposites.", tutorLine: "What is the opposite of 'hot'?", interaction: "tap_image", choices: [{ id: "a", label: "Cold", emoji: "🥶", isCorrect: true }, { id: "b", label: "Warm", emoji: "🌡️", isCorrect: false }, { id: "c", label: "Fast", emoji: "⚡", isCorrect: false }, { id: "d", label: "Big", emoji: "🐘", isCorrect: false }], sceneEmoji: "🔄", difficulty: "medium", brainMeasures: ["vocabulary", "antonyms"] },
    ],
    hard: [
      { id: "sp_h1", title: "Language Lab", narration: "You're ready for the advanced studio! Let's explore expressions.", tutorLine: "What does 'break a leg' mean?", interaction: "tap_word", choices: [{ id: "a", label: "Good luck!", emoji: "🍀", isCorrect: true }, { id: "b", label: "Be careful", emoji: "⚠️", isCorrect: false }, { id: "c", label: "Run fast", emoji: "🏃", isCorrect: false }, { id: "d", label: "Sit down", emoji: "🪑", isCorrect: false }], sceneEmoji: "🎙️", difficulty: "hard", brainMeasures: ["figurative language"] },
      { id: "sp_h2", title: "Context Clues", narration: "Some words have different meanings depending on how we use them.", tutorLine: "In 'I need to bat the ball', what does 'bat' mean?", interaction: "tap_word", choices: [{ id: "a", label: "Hit", emoji: "🏏", isCorrect: true }, { id: "b", label: "An animal", emoji: "🦇", isCorrect: false }, { id: "c", label: "A blanket", emoji: "🛏️", isCorrect: false }, { id: "d", label: "A bag", emoji: "👜", isCorrect: false }], sceneEmoji: "🔍", difficulty: "hard", brainMeasures: ["multiple meanings", "context clues"] },
      { id: "sp_h3", title: "Inference Station", narration: "Let's read between the lines!", tutorLine: "Maria grabbed her umbrella before leaving. What can you infer?", interaction: "tap_image", choices: [{ id: "a", label: "It might rain", emoji: "🌧️", isCorrect: true }, { id: "b", label: "She is hungry", emoji: "🍕", isCorrect: false }, { id: "c", label: "She is happy", emoji: "😊", isCorrect: false }, { id: "d", label: "It is bedtime", emoji: "🌙", isCorrect: false }], sceneEmoji: "🧠", difficulty: "hard", brainMeasures: ["inference", "pragmatic language"] },
    ],
  },
  pixel_puzzle_palace: {
    easy: [
      { id: "ef_e1", title: "Pattern Path", narration: "Welcome to my puzzle palace! The floor has a pattern. Can you complete it?", tutorLine: "Red, Blue, Red, Blue, ___?", interaction: "tap_image", choices: [{ id: "a", label: "Red", emoji: "🔴", isCorrect: true }, { id: "b", label: "Green", emoji: "🟢", isCorrect: false }, { id: "c", label: "Yellow", emoji: "🟡", isCorrect: false }], sceneEmoji: "🧩", difficulty: "easy", brainMeasures: ["pattern recognition"] },
      { id: "ef_e2", title: "Memory Bridge", narration: "Look carefully! I'll show you some items and then they'll hide.", tutorLine: "Which item did you see first?", interaction: "tap_image", choices: [{ id: "a", label: "Star", emoji: "⭐", isCorrect: true }, { id: "b", label: "Moon", emoji: "🌙", isCorrect: false }, { id: "c", label: "Sun", emoji: "☀️", isCorrect: false }], sceneEmoji: "🌉", difficulty: "easy", brainMeasures: ["working memory"] },
      { id: "ef_e3", title: "Which Comes Next", narration: "These things go in a special order. What comes next?", tutorLine: "1, 2, 3, ___?", interaction: "tap_image", choices: [{ id: "a", label: "4", emoji: "4️⃣", isCorrect: true }, { id: "b", label: "1", emoji: "1️⃣", isCorrect: false }, { id: "c", label: "7", emoji: "7️⃣", isCorrect: false }], sceneEmoji: "🔢", difficulty: "easy", brainMeasures: ["sequencing"] },
      { id: "ef_e4", title: "Odd One Out", narration: "One of these doesn't belong with the others. Can you find it?", tutorLine: "Which one is NOT a fruit?", interaction: "tap_image", choices: [{ id: "a", label: "Car", emoji: "🚗", isCorrect: true }, { id: "b", label: "Apple", emoji: "🍎", isCorrect: false }, { id: "c", label: "Banana", emoji: "🍌", isCorrect: false }], sceneEmoji: "🤔", difficulty: "easy", brainMeasures: ["categorization"] },
      { id: "ef_e5", title: "Follow the Steps", narration: "Let's follow instructions carefully! One step at a time.", tutorLine: "First clap, then jump. What do you do FIRST?", interaction: "tap_image", choices: [{ id: "a", label: "Clap", emoji: "👏", isCorrect: true }, { id: "b", label: "Jump", emoji: "🦘", isCorrect: false }, { id: "c", label: "Sit", emoji: "🪑", isCorrect: false }], sceneEmoji: "📋", difficulty: "easy", brainMeasures: ["following directions", "task initiation"] },
    ],
    medium: [
      { id: "ef_m1", title: "Sorting Challenge", narration: "Quick! Sort these by color... wait, now sort by shape instead!", tutorLine: "You were sorting by color. Now which group does the BLUE TRIANGLE go in?", interaction: "tap_image", choices: [{ id: "a", label: "Triangles", emoji: "🔺", isCorrect: true }, { id: "b", label: "Blue things", emoji: "🔵", isCorrect: false }, { id: "c", label: "Small things", emoji: "🤏", isCorrect: false }, { id: "d", label: "Circles", emoji: "⭕", isCorrect: false }], sceneEmoji: "🎯", difficulty: "medium", brainMeasures: ["cognitive flexibility"] },
      { id: "ef_m2", title: "What Would You Do?", narration: "Sometimes we need to think about what to do next!", tutorLine: "You spill juice on the table. What should you do first?", interaction: "tap_image", choices: [{ id: "a", label: "Get a towel", emoji: "🧻", isCorrect: true }, { id: "b", label: "Pour more juice", emoji: "🧃", isCorrect: false }, { id: "c", label: "Walk away", emoji: "🚶", isCorrect: false }, { id: "d", label: "Cry", emoji: "😢", isCorrect: false }], sceneEmoji: "💡", difficulty: "medium", brainMeasures: ["problem solving", "impulse control"] },
      { id: "ef_m3", title: "Maze Mind", narration: "Think ahead! Which path leads to the treasure?", tutorLine: "The path goes: right, up, right. Where do you end up?", interaction: "tap_image", choices: [{ id: "a", label: "Top right", emoji: "↗️", isCorrect: true }, { id: "b", label: "Bottom left", emoji: "↙️", isCorrect: false }, { id: "c", label: "Center", emoji: "⭕", isCorrect: false }, { id: "d", label: "Top left", emoji: "↖️", isCorrect: false }], sceneEmoji: "🗺️", difficulty: "medium", brainMeasures: ["spatial reasoning", "planning"] },
      { id: "ef_m4", title: "Rule Changer", narration: "The rules just changed! Can you switch?", tutorLine: "Before: clap for circles. NEW RULE: clap for squares. A square appears! What do you do?", interaction: "tap_image", choices: [{ id: "a", label: "Clap", emoji: "👏", isCorrect: true }, { id: "b", label: "Stay still", emoji: "🧍", isCorrect: false }, { id: "c", label: "Jump", emoji: "🦘", isCorrect: false }, { id: "d", label: "Shake head", emoji: "🙅", isCorrect: false }], sceneEmoji: "🔀", difficulty: "medium", brainMeasures: ["cognitive flexibility", "inhibition"] },
    ],
    hard: [
      { id: "ef_h1", title: "Strategy Master", narration: "The ultimate puzzle! This requires planning ahead.", tutorLine: "You have a big project due Friday. What's the best approach?", interaction: "tap_image", choices: [{ id: "a", label: "Break it into small steps", emoji: "📋", isCorrect: true }, { id: "b", label: "Wait until Thursday", emoji: "⏰", isCorrect: false }, { id: "c", label: "Hope it goes away", emoji: "🤞", isCorrect: false }, { id: "d", label: "Copy someone else", emoji: "📄", isCorrect: false }], sceneEmoji: "🏰", difficulty: "hard", brainMeasures: ["planning", "task initiation"] },
      { id: "ef_h2", title: "Priority Puzzle", narration: "You have three things to do. Which order makes the most sense?", tutorLine: "Tasks: pack lunch, eat lunch, buy groceries. What order?", interaction: "tap_image", choices: [{ id: "a", label: "Buy, pack, eat", emoji: "🛒", isCorrect: true }, { id: "b", label: "Eat, buy, pack", emoji: "🍽️", isCorrect: false }, { id: "c", label: "Pack, eat, buy", emoji: "🎒", isCorrect: false }, { id: "d", label: "Any order", emoji: "🎲", isCorrect: false }], sceneEmoji: "📊", difficulty: "hard", brainMeasures: ["planning", "organization"] },
      { id: "ef_h3", title: "Distraction Shield", narration: "Staying focused is a superpower! Let's practice.", tutorLine: "You're doing homework but hear a fun TV show. What's the best choice?", interaction: "tap_image", choices: [{ id: "a", label: "Finish homework first", emoji: "📚", isCorrect: true }, { id: "b", label: "Watch TV now", emoji: "📺", isCorrect: false }, { id: "c", label: "Do both at once", emoji: "🤹", isCorrect: false }, { id: "d", label: "Give up", emoji: "😩", isCorrect: false }], sceneEmoji: "🛡️", difficulty: "hard", brainMeasures: ["impulse control", "sustained attention"] },
    ],
  },
};

export { FALLBACK_ACTIVITIES };
