#!/usr/bin/env tsx
/**
 * Provision the Stripe Products and Prices that billing-svc expects.
 *
 * What it creates (idempotent — re-running matches by metadata.aivo_kind):
 *   - Product "AIVO Single Learner"   → recurring price ($24.99/mo) → STRIPE_PRICE_SINGLE
 *   - Product "AIVO Family"           → recurring price ($19.99/mo) → STRIPE_PRICE_FAMILY
 *   - Product "AIVO Tutor Add-on"     → recurring price ($4.99/mo)  → STRIPE_PRICE_TUTOR_ADDON
 *
 * Required: STRIPE_SECRET_KEY (test or live). Run from repo root:
 *
 *   STRIPE_SECRET_KEY=sk_test_... npx tsx scripts/stripe-setup.ts
 *
 * Output: a block of shell-export lines you can paste into your env or
 * a `.env` file. Existing matching Products/Prices are reused — the
 * script never creates duplicates.
 */
import Stripe from "stripe";

interface Spec {
  envVar: string;
  productName: string;
  productKind: string;
  unitAmountCents: number;
  description: string;
}

const SPECS: Spec[] = [
  {
    envVar: "STRIPE_PRICE_SINGLE",
    productName: "AIVO Single Learner",
    productKind: "plan:single",
    unitAmountCents: 2499,
    description: "Single learner plan — ELA + Math tutors included, add extras at $4.99/mo.",
  },
  {
    envVar: "STRIPE_PRICE_FAMILY",
    productName: "AIVO Family",
    productKind: "plan:family",
    unitAmountCents: 1999,
    description: "Family plan — 2+ learners, ELA + Math tutors included, add extras at $4.99/mo.",
  },
  {
    envVar: "STRIPE_PRICE_TUTOR_ADDON",
    productName: "AIVO Tutor Add-on",
    productKind: "addon:tutor",
    unitAmountCents: 499,
    description: "$4.99/mo per additional AI tutor. The chosen tutor SKU is carried in subscription-item metadata.",
  },
];

const METADATA_KEY = "aivo_kind";

async function findProduct(stripe: Stripe, kind: string): Promise<Stripe.Product | null> {
  const search = await stripe.products.search({
    query: `metadata['${METADATA_KEY}']:'${kind}' AND active:'true'`,
    limit: 1,
  });
  return search.data[0] ?? null;
}

async function findRecurringPrice(
  stripe: Stripe,
  productId: string,
  unitAmount: number,
): Promise<Stripe.Price | null> {
  // The search index can lag a few seconds; for setup correctness we
  // prefer the list API filtered by product so re-runs immediately find
  // a freshly-created price.
  for await (const price of stripe.prices.list({ product: productId, active: true, limit: 100 })) {
    if (
      price.unit_amount === unitAmount &&
      price.recurring?.interval === "month" &&
      price.currency === "usd"
    ) {
      return price;
    }
  }
  return null;
}

async function provision(stripe: Stripe, spec: Spec): Promise<{ envVar: string; priceId: string; reused: boolean }> {
  let product = await findProduct(stripe, spec.productKind);
  let productReused = !!product;
  if (!product) {
    product = await stripe.products.create({
      name: spec.productName,
      description: spec.description,
      metadata: { [METADATA_KEY]: spec.productKind },
    });
  }

  let price = await findRecurringPrice(stripe, product.id, spec.unitAmountCents);
  let priceReused = !!price;
  if (!price) {
    price = await stripe.prices.create({
      product: product.id,
      currency: "usd",
      unit_amount: spec.unitAmountCents,
      recurring: { interval: "month" },
      metadata: { [METADATA_KEY]: spec.productKind },
    });
  }

  const reused = productReused && priceReused;
  return { envVar: spec.envVar, priceId: price.id, reused };
}

async function main(): Promise<void> {
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) {
    console.error("STRIPE_SECRET_KEY is required. Run with: STRIPE_SECRET_KEY=sk_test_... npx tsx scripts/stripe-setup.ts");
    process.exit(2);
  }
  const stripe = new Stripe(key, {
    apiVersion: "2025-01-27.acacia" as Stripe.LatestApiVersion,
    typescript: true,
  });

  const results: Array<{ envVar: string; priceId: string; reused: boolean }> = [];
  for (const spec of SPECS) {
    process.stderr.write(`[stripe-setup] ${spec.productKind} … `);
    const r = await provision(stripe, spec);
    results.push(r);
    process.stderr.write(`${r.priceId} (${r.reused ? "reused" : "created"})\n`);
  }

  // Print env exports on stdout for piping into a file.
  console.log("# Generated by scripts/stripe-setup.ts");
  console.log(`# Stripe mode: ${key.startsWith("sk_live_") ? "LIVE" : "test"}`);
  for (const r of results) {
    console.log(`${r.envVar}=${r.priceId}`);
  }
}

main().catch((err) => {
  console.error("[stripe-setup] failed:", err?.message ?? err);
  process.exit(1);
});
