import type { InterestTheme } from "../types.js";

export const SEED_THEMES: readonly InterestTheme[] = [
  {
    slug: "dinosaurs",
    label: "Dinosaurs",
    nouns: ["T-Rex", "Triceratops", "Stegosaurus", "Brachiosaurus", "Velociraptor", "fossil", "egg"],
    verbs: ["stomp", "roar", "hatch", "dig", "spot"],
    assetNamespaces: ["dinos"],
    ageBands: ["PK", "K-2", "3-5", "6-8"],
    sensoryCautions: ["loud_audio"],
  },
  {
    slug: "trains",
    label: "Trains",
    nouns: ["steam train", "freight train", "caboose", "track", "tunnel", "whistle"],
    verbs: ["chug", "whistle", "couple", "haul"],
    assetNamespaces: ["trains"],
    ageBands: ["PK", "K-2", "3-5"],
    sensoryCautions: ["loud_audio"],
  },
  {
    slug: "space",
    label: "Space",
    nouns: ["rocket", "planet", "moon", "astronaut", "comet", "satellite"],
    verbs: ["launch", "orbit", "explore", "land"],
    assetNamespaces: ["space"],
    ageBands: ["K-2", "3-5", "6-8", "9-12"],
  },
  {
    slug: "ocean",
    label: "Ocean Life",
    nouns: ["whale", "dolphin", "octopus", "shark", "coral", "tide pool"],
    verbs: ["swim", "dive", "splash", "glide"],
    assetNamespaces: ["ocean"],
    ageBands: ["PK", "K-2", "3-5", "6-8"],
  },
  {
    slug: "music",
    label: "Music",
    nouns: ["drum", "piano", "guitar", "song", "rhythm"],
    verbs: ["strum", "tap", "sing", "drum"],
    assetNamespaces: ["music"],
    ageBands: ["PK", "K-2", "3-5", "6-8", "9-12"],
    sensoryCautions: ["loud_audio"],
  },
  {
    slug: "vehicles",
    label: "Vehicles",
    nouns: ["fire truck", "tractor", "bulldozer", "ambulance", "rocket"],
    verbs: ["drive", "honk", "lift", "haul"],
    assetNamespaces: ["vehicles"],
    ageBands: ["PK", "K-2", "3-5"],
    sensoryCautions: ["loud_audio"],
  },
  {
    slug: "animals_farm",
    label: "Farm Animals",
    nouns: ["cow", "sheep", "pig", "goat", "chicken", "horse"],
    verbs: ["graze", "moo", "trot"],
    assetNamespaces: ["farm"],
    ageBands: ["PK", "K-2"],
  },
  {
    slug: "weather",
    label: "Weather",
    nouns: ["cloud", "rain", "snowflake", "thunder", "rainbow"],
    verbs: ["fall", "shine", "blow"],
    assetNamespaces: ["weather"],
    ageBands: ["K-2", "3-5"],
    sensoryCautions: ["flashing"],
  },
] as const;
