/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health probe (root) */
        get: operations["learningHealthRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health probe */
        get: operations["learningHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent sessions for a learner */
        get: operations["listLearningSessions"];
        put?: never;
        /**
         * Start a learning session
         * @description Creates a lesson session for a learner. When `contentType` is `THERAPY_SESSION` the row is short-circuited as a manual therapist log; otherwise content generation is invoked and the response carries the generated lesson body.
         */
        post: operations["createLearningSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/sessions/{sessionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a learning session
         * @description Marks a lesson session COMPLETED, computes XP and completion quality from per-beat signals, and rolls mastery updates into the gradebook.
         */
        post: operations["completeLearningSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/gradebook/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert a single gradebook skill */
        post: operations["updateGradebook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/gradebook/{learnerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch gradebook entries for a learner */
        get: operations["getGradebook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/path/{learnerId}/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get (or initialize) a subject learning path */
        get: operations["getLearningPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/path/{learnerId}/{subject}/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initialize a subject learning path
         * @description Idempotent: returns the existing path with `status: "already_exists"` if one is present, otherwise creates one with default topics and best-effort upgrades to LLM-personalized topics.
         */
        post: operations["initLearningPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/path/{learnerId}/{subject}/refresh-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh a learning path's topic sequence from the curriculum engine */
        post: operations["refreshLearningPathTopics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning/path/{learnerId}/{subject}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance a learner along their subject learning path
         * @description Returns one of `advanced`, `path_complete`, or `needs_practice` based on the learner's current mastery vs. the functioning-level threshold for the next topic.
         */
        post: operations["advanceLearningPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    learningHealthRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        service: string;
                        /** Format: date-time */
                        timestamp: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    learningHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        service: string;
                        /** Format: date-time */
                        timestamp: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listLearningSessions: {
        parameters: {
            query: {
                learnerId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": ({
                        id?: string;
                        tenantId?: string;
                        learnerId?: string;
                        tutorSku?: string;
                        subject?: string;
                        status?: string;
                        contentType?: string;
                        functioningLevel?: null | string;
                        durationSeconds?: number;
                        xpEarned?: null | number;
                        /** Format: date-time */
                        startedAt?: string;
                        /** Format: date-time */
                        completedAt?: null | string;
                        sessionData?: null | {
                            [key: string]: unknown;
                        };
                        masteryAfter?: null | {
                            [key: string]: unknown;
                        };
                        brainContextSnapshot?: null | {
                            [key: string]: unknown;
                        };
                    } & {
                        [key: string]: unknown;
                    })[];
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createLearningSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    learnerId: string;
                    tutorSku: string;
                    topic?: string;
                    contentType?: string;
                    sessionDate?: string;
                    durationMinutes?: number | string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessionId: string;
                        status: string;
                        content?: null | string;
                        qualityScore?: null | number;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        qualityScore?: null | number;
                        qualityGateLog?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    completeLearningSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    masteryUpdates?: {
                        [key: string]: number;
                    };
                    xpEarned?: number;
                    beatsCompleted?: number;
                    beatsTotal?: number;
                    correctAnswers?: number;
                    attemptedAnswers?: number;
                    engagementBeats?: number;
                    breaksUsed?: number;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        sessionId: string;
                        xpEarned?: number;
                        completionQuality?: null | number;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateGradebook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    learnerId: string;
                    skill: string;
                    masteryScore?: number;
                    sessionType?: string;
                    xpEarned?: number;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        skill: string;
                        masteryScore?: null | number;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getGradebook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learnerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": ({
                        id?: string;
                        tenantId?: string;
                        learnerId?: string;
                        subject?: string;
                        skill?: string;
                        masteryScore?: null | number;
                        attemptsCount?: null | number;
                        trend?: null | string;
                        /** Format: date-time */
                        lastAssessedAt?: null | string;
                        /** Format: date-time */
                        updatedAt?: null | string;
                    } & {
                        [key: string]: unknown;
                    })[];
                };
            };
        };
    };
    getLearningPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learnerId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        tenantId?: string;
                        learnerId?: string;
                        subject?: string;
                        topicSequence?: string[];
                        completedTopics?: string[];
                        currentTopic?: null | string;
                        masteryMap?: {
                            [key: string]: unknown;
                        };
                        /** Format: date-time */
                        updatedAt?: null | string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    initLearningPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learnerId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "already_exists" | "created";
                        path: {
                            id?: string;
                            tenantId?: string;
                            learnerId?: string;
                            subject?: string;
                            topicSequence?: string[];
                            completedTopics?: string[];
                            currentTopic?: null | string;
                            masteryMap?: {
                                [key: string]: unknown;
                            };
                            /** Format: date-time */
                            updatedAt?: null | string;
                        } & {
                            [key: string]: unknown;
                        };
                        personalized?: boolean;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    refreshLearningPathTopics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learnerId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        path: {
                            id?: string;
                            tenantId?: string;
                            learnerId?: string;
                            subject?: string;
                            topicSequence?: string[];
                            completedTopics?: string[];
                            currentTopic?: null | string;
                            masteryMap?: {
                                [key: string]: unknown;
                            };
                            /** Format: date-time */
                            updatedAt?: null | string;
                        } & {
                            [key: string]: unknown;
                        };
                        topicCount: number;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        error: string;
                        topicSequence?: string[];
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    advanceLearningPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learnerId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        previousTopic?: null | string;
                        nextTopic?: null | string;
                        currentTopic?: null | string;
                        masteryScore?: number;
                        thresholdRequired?: number;
                        functioningLevel?: string;
                        subject?: string;
                        completedCount?: number;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
