image:
  repository: ghcr.io/artpromedia
  pullPolicy: Always
  tag: latest

replicaCount: 1

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

env:
  NODE_ENV: staging
  LOG_LEVEL: debug
  LOG_FORMAT: json

serviceMonitor:
  enabled: false

networkPolicy:
  enabled: false
